### ISSUE TITLE
Firefox, Edit shortcut keys button in options, open Manage Extension Shortcuts

### ISSUE THREAD

**Issue by duianto** [ken107/read-aloud#104]
### Firefox, Edit shortcut keys button in options, open Manage Extension Shortcuts
The `Edit shortcut keys` button in the extension options, opens a `shortcuts.html` page that shows the default shortcuts hard coded. They don't change even though the keys have been changed on the Firefox `Manage Extensions Shortcuts` page, to use `shift + alt` as the modifiers, because another extension [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en) uses `alt+p` for toggling tab pinning.

The `Edit shortcut keys` should probably open the Firefox `Manage Extension Shortcuts` page. Then they can be edited and the current shortcuts will be visible.

The Manage Extension Shortcuts page can be found by:
- Right clicking on the extensions toolbar icon
- Choosing Manage Extension
- To the top right there's a button with a Cog wheel icon and a down arrow
(the mouse over tooltip says: Tools for all add-ons)
When it's clicked, then a menu opens with the last entry being:
Manage Extension Shortcuts

### Notes
`shortcuts.html` might just be a work in progress page and this already is on the todo list.

#### System info:
Read Aloud 1.14.0
Firefox 68.0.1
Windows 1903

**Comment by ken107** [comment]
Thank you for the detailed info!  Indeed changing extension shortcut keys wasn't possible in earlier versions, so I just put an instruction page for the default keys.

Now, we can change that page to instruct how to open the Manage Extension Shortcuts page.  It would be nice if we can open that page automatically for them, but it doesn't look to be possible.

We'll get to this soon.

**Comment by tonglil** [comment]
How can I change the shortcut keys in Firefox? I don't see a page to do that, where as Chrome has chrome://extensions/shortcuts

**Comment by escape0707** [comment]
I suggest to add OP's instruction into the `shortcuts.html`.
