### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by S8D** [ken107/read-aloud#105]
Mình xin đóng góp với tác giả bằng tiếng Việt nhé!
Chức năng hiện tại thì mình thấy tạm ổn.
Còn về giao diện thì mình thấy có thể bôi đen trực tiếp lên trang Web hiện tại luôn cho đẹp. Mình nhớ không lầm thì dạo trước Microsoft Edge có chức năng đọc tiếng Việt khá hay và dễ nhìn. Màu nền bôi trong suốt thay đổi và tương phản theo màu chữ để thấy rõ chữ khi bôi và không làm quá nổi.
Cám ơn tác giả vì bỏ công làm tiện ích hữu ích này nhé!
P/s: Xin lỗi vì mình không hiểu rõ api hỗ trợ của từng nền tảng khác nhau nên hạn chế tính năng. Mình dùng Firefox

**Comment by ken107** [comment]
Merged into #13
