### ISSUE TITLE
Wave-net permissions

### ISSUE THREAD

**Issue by tentaman** [ken107/read-aloud#111]
When i click on the permissions for wave net to bring me to the [cloud url](https://cloud.google.com/text-to-speech/#convert-your-text-to-speech-right-now).Would it be possible to add a way to just attach my .json key to the extention? or would i have to modify this and compile it?

**Comment by ken107** [comment]
Please go to the APIs and Services section in the Google Cloud console and create an API key.  Then go to Read Aloud options, in the Voice dropdown scroll to the bottom and choose Enable Custom Voices.
In there you can enter the API key and it'll use your account.
