### ISSUE TITLE
Easy switch between favorite voices feature

### ISSUE THREAD

**Issue by truealisa** [ken107/read-aloud#117]
Possibility to narrow down the list of voices by choosing certain languages is great. But I think it would be extremely useful for anybody who like me used to read/listen in multiple languages to be able to add voices to favorites and then to switch between them without searching among all the voices I never use. Thanks!

**Comment by ken107** [comment]
You can now select a preferred voice for each language.  Please go to Options, in the Voice dropdown choose "Auto select".  Then click the pencil icon to the left to open Language Options.  In here, select the languages you want, and under each language choose a voice that will be used by default for that language

I'll close this ticket for now.  If you'd like something different, we can reopen it.  Thank you!  c98096d
