### ISSUE TITLE
paragraph skipping

### ISSUE THREAD

**Issue by vimalk78** [ken107/read-aloud#12]
the paragraph starting with "We can represent these three factors" is missed

<img width="1224" alt="screen shot 2017-09-05 at 9 22 07 pm" src="https://user-images.githubusercontent.com/3284044/30070192-51fcab8c-9280-11e7-950c-ff2118daac7f.png">

http://neuralnetworksanddeeplearning.com/chap1.html

**Comment by ken107** [comment]
Hi, thanks for reporting

This is due to error in the article's HTML markup.  I have not a solution for this yet.

**Comment by ken107** [comment]
New algorithm should pick it up now!
