### ISSUE TITLE
Doesn't work in Firefox Private Browsing Mode

### ISSUE THREAD

**Issue by brycekottke** [ken107/read-aloud#128]
Read Aloud plugin doesn't work in Firefox private browsing mode. Details below.

**Operating System**
 Debian 10 (buster)
**Firefox Version**
68.4.1esr

**Issue**
When highlighting text and clicking the Read Aloud plugin button in the top right hand corner it just loads the yellow text box and the icon just spins. If you go into settings and click `Test` all it says is `master is null`

**Comment by ken107** [comment]
https://discourse.mozilla.org/t/getbackgroundpage-in-private-mode/14046/12
