### ISSUE TITLE
Inline highlighting suggestion?

### ISSUE THREAD

**Issue by cryoteeth** [ken107/read-aloud#13]
It'd be great if there was an option to have the text of the webpage itself be highlighted!

**Comment by ken107** [comment]
Ah, indeed, it would be the holy grail!

**Comment by drcege** [comment]
I tried many read/speak extensions in the Chrome webstore and found yours is the best.  After pause / play, it is not easy to find the corresponding location.  It'd be perfect if the text highlight is inline!

**Comment by aaman-git** [comment]
> Ah, indeed, it would be the holy grail!

any updates on this feature?

**Comment by ken107** [comment]
Sorry, this is so difficult to do.  When highlighting, we'll need to surgically operate on the DOM structure to create the highlight overlay.  The challenge is coming up with an algorithm to deal with the variety of website markups in a general way.  Added to that, we are also breaking up the text not according to the article's paragraph structure, but according to the requirements of the voice engine.

**Comment by mfrimannm** [comment]
What about when reading pdf, would be so awesome.

**Comment by ken107** [comment]
merge into #179
