### ISSUE TITLE
[docs] Add features, screenshots and guides

### ISSUE THREAD

**Issue by atb00ker** [ken107/read-aloud#132]
Hi,

I've seen this app on market so many times but only installed it today after reading the code on GitHub and realizing that I can use GCP wavenet voices as well.
It's a shame that such a feature rich application doesn't have proper documentation.

**Comment by atb00ker** [comment]
I would like to help out with a part of documentation if you are open to the idea to listing features and guides in docs. :smile:

**Comment by ken107** [comment]
Please do!  Perhaps we can start with listing features in the README?

**Comment by atb00ker** [comment]
Sounds good, I'll get back to this as soon as possible! :smile:

**Comment by atb00ker** [comment]
**Update:** Gotten busy with day job, I'll try to take some time out as soon as possible! :smile:
