### ISSUE TITLE
Use of pico2wave under linux?

### ISSUE THREAD

**Issue by liar666** [ken107/read-aloud#140]
Hi,

The voice under linux is awful... I recenty discovered pico2wave, which has a nice voice. Would it be possible to switch to that voice under linux?
Or maybe I have to ask FF to make the switch?

PS: a script I worte that allows to read any selected text in Linux
```
#!/usr/bin/env bash

# Associate this script with xbinkeysrc or XFCE to CTRL-F9 or anything free key combo!

## apt install libttspico-utils xsel
## apt install mplayer  # we could use sox to change the rate (but pitch would change too)

FIFO=/tmp/test.wav

LANG=$(cat /tmp/CURRENT_LANG || echo "fr-FR") # "en-US"
SPEED="1.4"


mkfifo "$FIFO"
  xsel | sed 's/^[[:print:]]//g' | sed 's/[[:space:]][[:space:]]*/ /g' | sed '/^\s*$/d' | pico2wave -w /tmp/test.wav -l $LANG & mplayer -af scaletempo -speed $SPEED "$FIFO"
\rm "$FIFO"
```

**Comment by ken107** [comment]
I had tried pico2wave before and found its quality to be not very good, compared to the other voices available in Read Aloud.  I'll check it out again and see.

**Comment by ken107** [comment]
We'll only target ML-based TTS engines moving forward.
