### ISSUE TITLE
Sử dụng phần mềm trong các trình đọc file pdf, word,.... trên website 

### ISSUE THREAD

**Issue by trionline29** [ken107/read-aloud#15]

**Comment by ken107** [comment]
Bạn có thể nói rõ yêu cầu của mình là gì không?

**Comment by trionline29** [comment]
Dạ khi mở file pdf trên google drive ra, bôi đen đoạn văn để đọc thì nó không đọc đoạn văn đó mà đọc từ trang đầu tiên, với word cũng vậy ? có cách nào để giải quyết tình thế không ạ anh ? thanks a.
