### ISSUE TITLE
Social media banner image for github project

### ISSUE THREAD

**Issue by mark05e** [ken107/read-aloud#155]
I made a basic banner for the project. Nothing too fancy. Could you set it up from the settings page?

![project-social-banner-v1](https://user-images.githubusercontent.com/1783193/81511744-26f64180-9324-11ea-8c3d-f3de0e65df50.png)

How to - https://help.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview

Sometime in future, need to update the readme to include illustration attribution to [Streamline Labs](https://lab.streamlineicons.com/)

**Comment by ken107** [comment]
OK, thanks!

**Comment by mark05e** [comment]
I did a test and found that the text gets cropped out when it is being displayed. I have updated the image. Could you update using this?

![project-social-banner-v2](https://user-images.githubusercontent.com/1783193/81548123-76208e80-9385-11ea-9582-e49a0b13130c.jpg)

Will need to include background attribution to [freepik.com](https://www.freepik.com/free-vector/colorful-memphis-design-background-vector_3893585.htm)

**Comment by ken107** [comment]
Replaced.  Yeah, I was wondering about the size as well.
