### ISSUE TITLE
IBM Watson Text to Speech terms of use

### ISSUE THREAD

**Issue by germanattanasio** [ken107/read-aloud#156]
I work as part of the IBM Watson team. Today after some digging, I found that this repo is using the `/synthesize` endpoint from the [Text to Speech demo](https://text-to-speech-demo.ng.bluemix.net/) in a chrome extension.
If you read the [terms of use](https://watson-developer-cloud.github.io/terms?name=Text-to-Speech%20Demo) you will know that's not allowed.

> You are authorized to use the Application and associated content for your personal use for informational purposes only. The Application is not intended to be used for productive or commercial purposes, and such use is not permitted.

While I like the idea behind this project, I think it will be better if you create your service instance rather than using the public demo.

I'm happy to help you migrate to use your instance; the only downside will be that you will have to pay for the usage.

PS: Before I found this repo we found a high amount of traffic and decided to change the endpoint, and that's why you had to do https://github.com/ken107/read-aloud/pull/151

**Comment by ken107** [comment]
Thank you for reaching out. I understand. We will remove the functionality from the app.
