### ISSUE TITLE
More topic tags

### ISSUE THREAD

**Issue by mark05e** [ken107/read-aloud#158]
I found more topic tags that could be used to identify in the [topics pages](https://github.com/topics) for project visibility.

- [browser-addon](https://github.com/topics/browser-addon)
- [browser-extension](https://github.com/topics/browser-extension)
- [webextension](https://github.com/topics/webextension)
- [webextensions](https://github.com/topics/webextensions)
- [chromium-extension](https://github.com/topics/chromium-extension)
- [edge-extension](https://github.com/topics/edge-extension)
- [firefox-extension](https://github.com/topics/firefox-extension)
- [firefox-extensions](https://github.com/topics/firefox-extensions)

**Comment by ken107** [comment]
Done, thank you!
