### ISSUE TITLE
Cannot read local files, "settings" not available.

### ISSUE THREAD

**Issue by tkzv** [ken107/read-aloud#162]
When I open a saved HTML file and try to use Read Aloud, I get a message "You need to grant Read Aloud access to file URLs in extension settings". When I click "settings", nothing happens. How do I allow it to read local files?

Firefox 76.0.1, Read Aloud 1.31.1.

**Comment by ken107** [comment]
Thank you, fixed in c0a8f34
Version 1.31.2 has just been published with this fix.  Please reopen if issue persists.
