### ISSUE TITLE
Embedded advertising and self promotions

### ISSUE THREAD

**Issue by ruffsl** [ken107/read-aloud#170]
I've noticed the read-aloud chrome extension will occasional embed adverts links within the text box drop down when reading aloud websites.

![image](https://user-images.githubusercontent.com/2293573/87346824-09517e00-c507-11ea-98e0-93b3d5c89240.png)

At first I had thought that is browser extension had been compromised. This would not have a first for such an innocuous seeming accessibility extension, e.g. "SpeakIt!":

> [My browser, the spy: How extensions slurped up browsing histories from 4M users](https://arstechnica.com/information-technology/2019/07/dataspii-inside-the-debacle-that-dished-private-data-from-apple-tesla-blue-origin-and-4m-people/)
>
> When we use browsers to make medical appointments, share tax returns with accountants, or access corporate intranets, we usually trust that the pages we access will remain private. DataSpii, a newly documented privacy issue in which millions of people’s browsing histories have been collected and exposed, shows just how much about us is revealed when that assumption is turned on its head.

I now see that that this Side Chatter extension is also Github project from the same author here, but would recommend that this fact be made abundantly clear in the self promotions text, least the read-aloud extension be removed being reported as suspect. This extension is also not acknowledged by the LSD Software page, making seem more if'y.     

https://github.com/ken107/side-chatter
https://lsdsoftware.com

**Comment by ken107** [comment]
Thank you, going forward, we will make clear that the promoted products are our own.

My plan is we will have a product showcase page, where we showcase other LSD Software projects.  And we will link to it as "Check out other LSD Software projects".

**Comment by ruffsl** [comment]
I saw another odd looking announcement today at the footer of the extension popup with the text:

> not sponsored by Phfizer

And again suspected one of my extensions had been compromised.
Checking the source code, I can see that announcements are added to the footer:

https://github.com/ken107/read-aloud/blob/03a773d17ea07d169794cbd81c32cf43fcb1105f/js/popup.js#L299

With announcements being fetched from the following URL:

https://github.com/ken107/read-aloud/blob/03a773d17ea07d169794cbd81c32cf43fcb1105f/js/popup.js#L274

https://github.com/ken107/read-aloud/blob/03a773d17ea07d169794cbd81c32cf43fcb1105f/docs/js/utils.js#L3

After curling that URL I was satisfied that the content was being served by the intended origin.

```sh
$ curl https://support.readaloud.app/read-aloud/announcement
```

```json
{
    "id": "phfizer",
    "text": "not sponsored by [Phfizer]",
    "link": "https://www.justice.gov/opa/pr/justice-department-announces-largest-health-care-fraud-settlement-its-history",
    "period": 1200
}
```

While I've no qualms with such activism, as the conflict of interest with Big Pharma lobbying public legislation is all too concerning, you may want to link your own blog, instead of anonymous or out of the blue looking URLs, to add a bit more authenticity and disclosure.

When extension start redirecting to unrelated links with respect to the extension's function, that sounds some alarms. Yet, if it was a redirect to something attributable to the authoring developer, then things would be more transparent.

**Comment by ken107** [comment]
You're right, redirecting to an own blog would be the proper approach.  Thanks
