### ISSUE TITLE
Adding additional SSML tags to JSON text data

### ISSUE THREAD

**Issue by PaulHBartley** [ken107/read-aloud#171]
Hi,

First of all, love this extension.

I've been using it with the GCP "premium" Wavenet voices. I'm interested in experimenting with adding SSML tags to the JSON text bundle that gets sent from Read Aloud to my GCP Text to Speech API.

The way I plan on doing this is to set up a "function" container on GCP as a REST endpoint to receive text in JSON, and then put the text through some processing that adds SSML tags to certain phrases, etc.

I was thinking it would be neat if I could re-route the JSON text bundle that your extension sends as a REST POST request. If possible, I would like to try to re-direct the POST request to my "function" container which would receive the JSON text bundle for processing first, and then it would send the text to the GCP TtS API for Wavenet playback.

How difficult do you think this would be? I know there's a section in one of your .js scripts that handles the POST API call to GCP TtS. Could it be as simple as changing this API request from GCP TtS to my "function" on GCP?

If so, and if it would be okay with you, I would like to do a fork and try it. However, I'm not familiar with how extensions are installed in Chrome. Maybe there's an easier way?

I'm a relative newbie with all of this stuff, so let me know if you have any questions or if anything doesn't make sense.

Thanks!
Paul

**Comment by ken107** [comment]
Hi Paul!

I assume you want to do this just for yourself?

If you want to modify the text that's sent to GCP, why don't you just modify the extension code right before it is sent to the GCP endpoint (https://github.com/ken107/read-aloud/blob/617a6acd71864ead4e24f6c781886c92a8c5d6ed/js/tts-engines.js#L845).  You could also change that URL to your function and do it on the server if you wish.

You can fork the repo, then clone it on your computer, then load it into Chrome as follows:
1) Open this URL: chrome://extensions/
2) Click "Load Unpacked"
3) Browse to the folder where you cloned the repo and select that folder

**Comment by PaulHBartley** [comment]
Hi, yes - this is just my own experiment for the time being.

Originally I thought of simply modifying your extension code in-line to add the SSML tags, but I'm thinking of eventually turning this into a reinforcement learning/NLP project, and for that reason I might as well set it up on the server in Python.

Thanks a lot for explaining the Chrome install process. Sounds pretty straightforward!
