### ISSUE TITLE
Handle multimedia keys

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#172]
chrome.command

**Comment by ken107** [comment]
After more deliberation, we decide against this, because for most people the media keys control their music. If we reroute these keys by default, it will confuse a lot of users.  There are online articles on how to prevent Chrome from hijacking media keys; clearly this could be a problem.

Nevertheless, while Read Aloud is reading, the Play/Pause media key actually works to pause/resume reading.  Otherwise users can use the designated shortcut keys <kbd>alt</kbd>+P, <kbd>alt</kbd>+O, <kbd>alt</kbd>+Comma, <kbd>alt</kbd>+Period to play/pause, stop, rewind, forward, respectively.  User can change these keys as well from the options page.

**Comment by Wild-Dog** [comment]
"Nevertheless, while Read Aloud is reading, the Play/Pause media key actually works to pause/resume reading."

No, it still doesn't. It'll work for ten seconds and play again, as it has for two years.
