### ISSUE TITLE
make clear which speach is generated on which system

### ISSUE THREAD

**Issue by nanderer** [ken107/read-aloud#188]
There are may reasons (privacy, metered internet connection) that would someone decide to use only local generated text to speech engines. so maybe you can make it more clear in the settings which engines are local and which are not (and under which privacy conditions they run (servers in EU or elswere, etc...)).

Maybe a force offline mode that hides all network-depended tts-engines would be nice.

Thanks a lot in advacne

thanks a lot in advance and keep up the good work

PS: probably thats also a problem with my system/tts software but ive got espeak installed also to be available with SAPI5, but it is not listed...

**Comment by ken107** [comment]
merge with #166
