### ISSUE TITLE
Is there a way to force the Read Aloud extension to speak in "Putonghua" only?

### ISSUE THREAD

**Issue by Thomasc5** [ken107/read-aloud#193]
On Firefox, Read Aloud (Google Translate Voice) would often speak in Cantonese (a Chinese dialect) rather than in Putonghua (普通话; i.e. standard Chinese).

May I ask is there a way to force Read Aloud to speak only in Putonghua? 

Thank you!

**Comment by Thomasc5** [comment]
After the recent update, Read Aloud now speaks only in Putonghua.  Thank you!

**Comment by ken107** [comment]
Thanks for the update.  Latest version fixed the Google Translate voices.  That must have done it.
