### ISSUE TITLE
Cantonese need to be an isolated option

### ISSUE THREAD

**Issue by ICHx** [ken107/read-aloud#195]
Currently, ChineseGoogletranslate is the only voice under Chinese, but there is no control for using either Mandarin or Cantonese.

An isolated Cantonese (or Chinese HK in google translate) option would be highly appreciated.

**Comment by helpme2k2** [comment]
second that

**Comment by ken107** [comment]
GoogleTranslate has only one voice for Chinese, unfortunately.

Have you tried one of the GoogleStandard yue voices?  I think they're HK.  Also the Microsoft Chinese HK.  Those voices require login/purchase, however.

**Comment by ken107** [comment]
https://support.google.com/translate/thread/45377850/unable-to-translate-english-to-cantonese-language-speaking-in-hong-kong-not-taiwan?hl=en
