### ISSUE TITLE
"Please sign in to use Premium Voice" loop

### ISSUE THREAD

**Issue by colourful-land** [ken107/read-aloud#199]
1. Follow [the instruct] to configure AWS access key id and secret access key, and, select a premium voice (in my case I selected Spanish (Castillano) Conchita voice.
2. Go to a new web page and click the button in the tool bar and see "Please sign in to use Premium Voice".
3. A window pops up asking me to sign in. I chose sign in with Google ID.
4. The window closes.
5. Go to a new web page and click the button in the tool bar and **still** sees "Please sign in to use Premium Voice".

**Comment by colourful-land** [comment]
Repeated the test by signing up with an email address, still failed the same way (after sign in, the pop window closes and the status is still Please sign in to use Premium Voice". Using the plugin installed a few minutes ago so must be latest. Using Firefox 84

**Comment by ken107** [comment]
Thank you for reporting this issue

**Comment by 96312** [comment]
It's still happening with google voices for your record. I came here to report just that.
