### ISSUE TITLE
Firefox plugin

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#20]
Add options_ui in manifest
Use speechSynthesis API instead of chrome.tts
no equivalent for chrome.ttsEngine so that will remain chrome-only

**Comment by ken107** [comment]
Version 1.3.1 is Firefox-ready!  https://addons.mozilla.org/en-US/firefox/addon/read-aloud/

**Comment by NukeManDan** [comment]
Link 404s :cry:

**Comment by ken107** [comment]
Thanks, FF has taken down the plugin.  I'm gonna need to make some fixes
