### ISSUE TITLE
Dev ơi làm ơn thêm chức năng xuất ra file audio/mp3 . Bạn có thể cho tôi xem quảng cáo vì điều đó 

### ISSUE THREAD

**Issue by ldb-258** [ken107/read-aloud#204]
Mình cần xuất ra file audio để nghe truyện trên điện thoại, tải về nghe dần lúc không có internet.
Mình sẵn sàng xem/ click vào quảng cáo vì điều này.
Nếu không thể, hãy giới thiệu mình trang web/app nào có chức năng như vậy cho tiếng việt với giới hạn >=5000 chữ

**Comment by ken107** [comment]
Merge into #159
