### ISSUE TITLE
Support Firefox Android > 86?

### ISSUE THREAD

**Issue by ghost** [ken107/read-aloud#206]
Thank you very much for the wonderful app.

I keep using it on Firefox 68 for Android, because Firefox add-ons website refuses to install it on 86 (current version). I think, ff-Android versions newer than 70 are affected. 

It's it even possible to update it for the new version?

**Comment by ken107** [comment]
I'm working with Scott DeVaney from Mozilla to get it on the addon store for the new Firefox Fenix. Earlier there was a bug that prevented Read Aloud from working, but that has been resolved. Now we are waiting for a freeze to be lifted and addon approvals to be resumed for Fenix.

**Comment by gotmax23** [comment]
If you want to use Read Aloud on Android in the meantime, Kiwi Browser is another option.

**Comment by Warden20** [comment]
+1

**Comment by lockywolf** [comment]
Is there anything we, users/testers can do to make thi)s work? (Maybe some programming needed?

**Comment by ken107** [comment]
Mozilla hasn't made any move on the Recommended extensions front yet, they're in some kind of internal roadblock.

But Firefox Nightly has a developer option to install any extensions you want.  I just verified that it works.
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

You'd want to create your own collection, add all the extensions you want to that collection, then follow the instruction to activate the collection on Firefox Nightly.  And those extensions will then appear in the addon manager.

**Comment by TheW0LVERIN3** [comment]
> 
> 
> Mozilla hasn't made any move on the Recommended extensions front yet, they're in some kind of internal roadblock.
> 
> But Firefox Nightly has a developer option to install any extensions you want. I just verified that it works. https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
> 
> You'd want to create your own collection, add all the extensions you want to that collection, then follow the instruction to activate the collection on Firefox Nightly. And those extensions will then appear in the addon manager.

I just tried this and came here to report that it asks for a permission for google translate voices and doesn't work right now, I can't grant the permission.

**Comment by ken107** [comment]
Thank you for the issue report

**Comment by lockywolf** [comment]
Can anything be done to help with this issue?
