### ISSUE TITLE
Shortcut key for "Read selected text"

### ISSUE THREAD

**Issue by 17721** [ken107/read-aloud#212]
Right now it's only either "Play/Pause" or "Stop". Can you add an option to assign a key for "Read selected text"? Right now it's only available only via mouse context menu (right-clicking on selected text).

**Comment by Warden20** [comment]
+1

**Comment by ken107** [comment]
Could you try selecting the text and then press the "Play/Pause" shortcut key?  I just tried it and it reads the selected text.

**Comment by ken107** [comment]
The default shortcut key for Play/Pause will read the selected text, or the whole document if no text is currently selected.  We shouldn't need a separate shortcut.
