### ISSUE TITLE
Read.Amazon.com no longer works

### ISSUE THREAD

**Issue by Arcyne** [ken107/read-aloud#218]
When attempting to read a Kindle book on the Amazon reader website no audio is played.  Looking at the screen the pages progress with the symptoms shown above.

**Comment by ken107** [comment]
Unfortunately, Amazon has changed their online reader and serve only images of the book content, not the actual text, ostensibly for copyright protection.  There isn't any workaround I don't think.  We have to renege support for the Kindle reader website.

**Comment by Arcyne** [comment]
Sigh, only thoughts are real time OCR or perhaps an accessibility API.

**Comment by ken107** [comment]
ce13fd360b0c1c3a50492b6e692410b088b46b08 uses OCR, will be in release 2.0
