### ISSUE TITLE
ReadAloud skips test in a button.

### ISSUE THREAD

**Issue by Hipposterous** [ken107/read-aloud#219]
My classes use acrobatiq.com for course material, which I read using ReadAloud.
Some words in the course material are wrapped in button tags, and acrobatiq treats them like tool tips when hovered or clicked. ReadAloud skips reading the text in a button.
Example HTML document to reproduce:
```html
<!DOCTYPE html>
<html>
<body>
This example text will <button>not actually</button> be read.
</body>
</html>
```

**Comment by ken107** [comment]
Semantically the text of a button tag  isn't part of the article's content and so it is ignored by the scraping algorithm.  I think we have to provide custom handling for this website.  To do that, I will need to login to the site and examine the HTML markup.  It looks like this site is available only to educational institutions and their students.  Do you have a temporary user login you're willing to share with me that I can use?  If so, please send it to me at support@lsdsoftware.com

If not, I could provide custom handling for the site that behaves similarly to the default algorithm except not skipping the button tag.  But I wouldn't be able to test and validate the fix.

**Comment by Hipposterous** [comment]
I can't provide a login (not even sure how mine works since I'm redirected there), but perhaps this will help:

It appears these `<button>` elements are not a child element of a form. Perhaps that can help as selection criteria.
Also, they all have the attribute `data-toggle="popover"`

```html
<button 
class="aiq term entry btn-link" 
id="59b7781ec765905a94dae286" 
data-toggle="popover" 
tabindex="0" 
data-container="body" 
data-trigger="hover" 
data-placement="top" 
data-html="true" 
data-template="<div class=&quot;popover aiq-extra-popover&quot; role=&quot;tooltip&quot;><div class=&quot;arrow&quot;></div><h3 class=&quot;popover-title&quot;></h3><div class=&quot;popover-content&quot;></div></div>" 
data-content="tooltip text goes here blah blah blah"
>Some button text</button>
```

**Comment by ken107** [comment]
I think this is sufficient to make an initial custom handler for this site, and we'll keep fixing it as necessary.  Thanks so much

**Comment by sqlHippo** [comment]
Thank you for the fix! 

Somehow it works when I press the ReadAloud button from the toolbar and let it read the entire page, but if I select a passage and invoke ReadAloud from the context menu (Firefox), it skips reading the button text.

I've included a screenshot in case it helps.

Browser is Firefox 92.

![image](https://user-images.githubusercontent.com/90177253/135775529-e58474bd-c9e1-487d-85b5-5096638700b5.png)

**Comment by ken107** [comment]
We are using the browser-defined function to grab the currently selected text. This means the button text isn't included in the selection. Unfortunately making a workaround is much more complicated than is warranted I'm afraid.

**Comment by sqlHippo** [comment]
Womp womp! Thank you for looking into it!
