### ISSUE TITLE
Integrate as widget into site

### ISSUE THREAD

**Issue by arvindpdmn** [ken107/read-aloud#222]
Rather than asking users to install browser plugin, has anyone used this code as a widget in their site? Any server-side support is needed for this?

**Comment by ken107** [comment]
Hello, you probably looking for https://readaloud.app?tab=embed-website

**Comment by arvindpdmn** [comment]
Thanks for the link. However, I was wondering if it can be hosted from my own server. The link you shared makes calls to `https://assets.sitespeaker.link`
