### ISSUE TITLE
Increase voice speed beyond 2x

### ISSUE THREAD

**Issue by africancup** [ken107/read-aloud#240]
Is it possible for the voice speed to be increased beyond 2x the normal speed? I understand this isn't available right now, but is it possible to make changes to the code to increase the speed limit? Or is this sort of thing locked by the voice module/tts engine?

**Comment by ken107** [comment]
Please go to Options and click the Pencil icon to the left of the Speed slider.  The slider will change to a textbox, in which you can enter a number up to 10x.  Let me know if that works

**Comment by africancup** [comment]
My mistake, I didn't try clicking on the pencil icon before! I see that it can go up 10, but I've only been able to get the default Google Translate voice up to 3.6 (which I understand is due to Google Translate limitations)
