### ISSUE TITLE
Firefox extension (Windows) not working after applying Arkenfox user.js privacy measures

### ISSUE THREAD

**Issue by abhiinav-18** [ken107/read-aloud#244]
The extension pop-up appear but won't work. Text get highlighted in the box and the option to select voice, volume and pitch are present however there is no sound from the reading extension.
Also, selecting a word and right-clicking produce no option to Read Aloud selected text.

I've tried the extension on profile with no Arkenfox user.js and it works fine there.

**Comment by behradJ** [comment]
I have the same issue here.

**Comment by behradJ** [comment]
> The extension pop-up appear but won't work. Text get highlighted in the box and the option to select voice, volume and pitch are present however there is no sound from the reading extension. Also, selecting a word and right-clicking produce no option to Read Aloud selected text.
> 
> I've tried the extension on profile with no Arkenfox user.js and it works fine there.

did you find anything?
