### ISSUE TITLE
Sao không đọc được trong google docs nữa nhỉ?

### ISSUE THREAD

**Issue by huuson889** [ken107/read-aloud#245]
Lúc trước đọc trong gg docs rất bình thường, bây giờ không đọc được nữa, yêu cầu phải cài Add-ons cùng tên, mà cài xong cũng không đọc được luôn, trả về như lúc trước đi. Làm ơn!!!

**Comment by ken107** [comment]
Vâng, Google Đocs thay đổi không còn xuất nội dung văn bản ra trình duyệt nữa á bạn.  Nên tiện ích không đọc được nữa, phải dùng Add-on mới đọc được nội dung văn bản.

Bạn cài Add-on, xong chọn ngôn ngữ Tiếng Việt, rồi chọn cái giọng tên là "Fallback".  Giọng đó sẽ đọc được tiếng việt

**Comment by huuson889** [comment]
Cái giọng Fallback đó bị lỗi Unknown TTS error và không mượt như chị google thời xưa á :((
Sao vẫn có 2 file gg docs của mình còn đọc bằng chrome extention được nè, lạ quá

**Comment by huuson889** [comment]
Anh xem lại cái tốc độ đọc của extention với, chỉnh cùng 1 mức mà tiếng anh nhanh hơn tiếng việt nhiều lắm

**Comment by ken107** [comment]
Bây giờ tạm thời đọc được Google Docs rồi.  Tuy nhiên mai mốt Google sẽ làm ko đọc đc nữa thì sẽ phải dùng cái addon.  Cám ơn bạn nhé.
