### ISSUE TITLE
[Feature request] Playback speed buttons in the main windows

### ISSUE THREAD

**Issue by iamashwin99** [ken107/read-aloud#247]
Hi 
Thank you so much for this very useful extension.
I just wanted to request if it would be possible to add the playback speed buttons on the home screen itself. And possibly add a keyboard shortcut for the same. Thanks in advance. 
Home page where the playback speed button would be useful:
![Home page where the playback speed button would be usefull](https://user-images.githubusercontent.com/46030335/148323398-84ddedeb-492e-4951-9339-81718ea017c4.png)
chrome://extensions/shortcuts page where we can add keyboard shortcuts:
![chrome://extensions/shortcuts page where we can add keyboard shortcuts](https://user-images.githubusercontent.com/46030335/148323433-9e8c8159-3f29-441a-916f-0f6aa602b76d.png)

**Comment by iamashwin99** [comment]
While the popup is in the playing state, the settings icon is disabled.
I would prefer if the settings icon remains there even while playback is going on so that I can change the speed and the voice etc. dynamically as the playback is going on (this gives easier feedback while changing speed for instance)

If this is not something the author is willing to update, could you please let me know how one would go about doing this, as I would very much like to fork it with this feature for my personal use.
I tried a bit of debugging and found out that popup.js toggles the settings button visibility continuously, https://github.com/ken107/read-aloud/blob/master/js/popup.js#L111 , I'm just not sure what modifications are required. Any help would be greatly appreciated.

**Comment by ken107** [comment]
You can replace that line with
```
$("#btnSettings").toggle(true);
```
That should keep it visible always.

However, the ability to change reading speed mid-speech depends on which voice the user are using.  Native TTS voices require the speech to be stopped and restarted with different parameters.  Cloud voices generate audio files, the speed of their playback can be modified mid-speech.  So you might need to do some extra work to make it work smoothly

**Comment by kellub** [comment]
I'd vote for this to be pulled in to the main branch if possible as well. I find myself changing the speed each time I view a different page, and it is a bit inconvenient to restart playback at the midpoint of a page once I have updated the settings.

**Comment by ken107** [comment]
merge with #329
