### ISSUE TITLE
Thêm tính năng tách Extension Button thành cửa số popup và highlight lsdsoftware.com khi đọc file pdf

### ISSUE THREAD

**Issue by DuongQuy123** [ken107/read-aloud#250]
Không biết bạn có thể giúp cho cái phần đọc khi nhấn Extension Button được chuyển thành một cái cửa sổ dạng popup của trình duyệt tách ra hẳn để dễ theo dõi được hay không nhỉ? Nó rất tốt để mình có thể theo dõi trong quá trình nghe tài liệu, mình dùng Linux nên có tính năng để một cửa số luôn nằm trên, nó sẽ rất tiện để nghe và xem, nhất là dạo gần đây mình dùng addon của bạn để nghe phát âm và học tiếng Anh, với người dùng hệ điều hành khác, mình nghĩ họ có thể thu nhỏ trình duyệt theo kiểu windows tilling hoặc cắm vào màn hình phụ để theo dõi, chứ hiện nay cái nút Extension Button cứ biết mất khi làm việc khác làm không theo dõi được, rất đáng tiếc.

Nếu không được, ở https://assets.lsdsoftware.com/read-aloud/page-scripts/pdf-upload.html để đọc file pdf của bạn, bạn có thể giúp nó highlight vàng đoạn đang đọc trong file pdf như khi ấn vào Extension Button được chứ? Nhìn nó sẽ trực quan hơn nhiều và dễ theo dõi tài liệu.

Cám ơn công sức của bạn, đây là một trong số top những addon trình duyệt tốt nhất mà mình hiện đang sử dụng hằng ngày.

**Comment by ken107** [comment]
Bạn vô chỗ Tùy Chọn, chọn cái này nó sẽ mở ra khung window riêng nhé

![image](https://user-images.githubusercontent.com/1976032/150652103-6025f367-7c1b-4862-b7f5-0b649f41b4e4.png)

**Comment by DuongQuy123** [comment]
Cám ơn bạn rất nhiều, đúng cái mình cần rồi, tại vì mình dùng chính trên Firefox nên không thấy được tùy chọn đó. Do Firefox có cái tab container tiện quá nên mình không chuyển qua Chrome dùng chính được, tuy nhiên, việc sử dụng addon của bạn cũng rất quan trọng nên mình sẽ chuyển sang dùng Chorme tạm trong khi đợi bạn có nâng cấp mới trong tương lai cho Firefox.

Cám ơn và trân trọng !

**Comment by ken107** [comment]
Cám ơn bạn đã kiên nhẫn nhé.  Firefox có tính năng rồi đó.  Chúc vui vẻ.

**Comment by DuongQuy123** [comment]
Tuyệt vời quá, cảm ơn bạn nhiều, mình dùng Chrome chỉ vì addon của bạn thôi :)), giờ tiện hơn rất rất nhiều rồi :)
Chúc các bạn luôn mạnh khỏe và hạnh phúc nhé :)
