### ISSUE TITLE
Can we avoid reading code line number?

### ISSUE THREAD

**Issue by XinyueZ** [ken107/read-aloud#256]
hey, 

the plugin works super, especially as long as I get elder and elder I prefer to listen+read instead only reading :) 

but, when there is code snipped, it reads line number, too. 

I dont mind reading code content, however, reading line number is a little bit over.

Can you improve?

E.g page https://machinelearningmastery.com/vector-norms-machine-learning/

**Comment by ken107** [comment]
There is no standard
