### ISSUE TITLE
Đọc cùng lúc 2 thứ tiếng và nhiều giọng trong 1 văn bản ?

### ISSUE THREAD

**Issue by trionline29** [ken107/read-aloud#26]

**Comment by ken107** [comment]
Vấn đề này khá khó khăn, nếu văn bản có 2 ngôn ngữ mà muốn dùng 2 giọng đọc khác nhau, thì phải phát hiện ngôn ngữ của từng chữ trong văn bản, không thiết thực cho lắm.

Trong mốt số trường hợp, bạn có thể sử dụng công cụ này:  https://ttstool.com

**Comment by trionline29** [comment]
Dạ em cảm ơn anh, nhưng anh ơi, nếu có chức năng thì em có thể dùng làm audiobook song ngữ vừa làm việc nhà vừa luyện tiếng Anh. 
Em sẽ dùng phần mềm so sánh bản dịch tương ứng với bản gốc sau đó dùng phần mềm đọc để khi giải lao em vừa nghe, em xin đề xuất giải pháp để đơn giản hóa vấn đề hơn:
1. Có thể dùng các ký hiệu đặc biệt để đánh dấu cho phần mềm biết đoạn nào là đoạn dịch, hoặc cần chuyển giọng đọc khác để người nghe bớt nhàm chán và tập trung hơn.
2. Chia thành 2 file bản gốc và bản dịch, có đánh số thứ tự dòng hoặc đoạn sẵn, phần mềm chỉ việc đọc xen kẽ anh-việt/việt anh.
Cảm ơn anh rất nhiều về phần mềm hữu ích. Hy vọng các chức năng này sẽ không tốn nhiều thời gian của anh ạ.
