### ISSUE TITLE
Not functioning inside of Flatpak sandbox

### ISSUE THREAD

**Issue by robert2343** [ken107/read-aloud#261]
I am running Librewolf (fork of Firefox), which I installed from Flatpak on Linux Mint (which is why it is in a sandbox), and I am trying to use the Google Translate English option, and every time I try to read anything aloud, it says "click here to start", and when I click there, that message goes away, then reappears after about a second. I get no sound. It works on normal Firefox, installed by default on my distribution. Does anyone know how to fix this or atleast something that Read Aloud uses that would be made unavailable by a sandbox?

**Comment by ken107** [comment]
Ah, that message appears when the browser prevents audio playback until an initial user interaction occurs. Clicking that link is supposed to provide that initial interaction and allows audio playback to proceed. Apparently it's not doing that for some reason. Needs investigation

**Comment by Juelzz** [comment]
🖕🏻🖕🏻🖕🏻🤣❤️

**Comment by DmitriyPekar** [comment]
I don't have the Real Aloud extension in librewolf working, either.

**Comment by robert2343** [comment]
Hi, just following up to see if anything has been done about this yet. No pressure if it hasn't. Just wondering.
Thanks

**Comment by ken107** [comment]
Sorry, I haven't had time to look into this.  We've run into this with the various forks of the main browsers.  As far as I can tell, it is not something we can workaround.

Basically when we call audio.play() it returns an error saying the user hasn't interacted with the page yet, and prevents the audio from being played.  So we display a link in the error message ("click here to start"), that's supposed to furnish that initial user gesture.  It worked for Brave (I think that's where we initially implemented it), but apparently not for many of the Firefox forks.
