### ISSUE TITLE
[BUG] Playback stuttering at each new line

### ISSUE THREAD

**Issue by 1778707** [ken107/read-aloud#265]
Just found some weird bug. When you right-click a text and press Play from context menu, the text plays okay as it inserts uniformly without line breaks (i.e., the same thing when you press Ctrl+Enter inside MS Word). But when you use a keyboard shortcut (play/pause), it inserts the text inside the plugin's window in a very strange manner. Is it possible to fix it? 

https://youtu.be/UrH4LQKu2pw

**Comment by ken107** [comment]
Could you attach your PDF file?  It would help a lot!  Thanks

**Comment by 1778707** [comment]
> Could you attach your PDF file? It would help a lot! Thanks

https://www.upload.ee/files/14034923/1.pdf.html
