### ISSUE TITLE
`You need to grand additional permissions to enable Google Translate voices` after installation

### ISSUE THREAD

**Issue by Kreyren** [ken107/read-aloud#277]
![2022-07-15_10-38](https://user-images.githubusercontent.com/11302521/179186750-7414b970-928b-401b-8ef3-8f4c312832c7.png)

The `permissions` is not clickable and i can't make it work

### Steps to reproduce
1. Install the extension
2. Try to make it read a text for you, bcs you hate reading and be dissapointed

#### Giving additional permissions
Tried enabling this in permissions which didn't help
![2022-07-15_10-40](https://user-images.githubusercontent.com/11302521/179187171-b9c07367-baa3-4c09-a910-29bdc4fc7d3b.png)
 
 ### Used system and environment
![2022-07-15_10-43](https://user-images.githubusercontent.com/11302521/179187636-097238a6-7bec-46ef-aacf-3d0fbc479f89.png)

```console
$ guix describe
Generation 19	čec 13 2022 21:48:56	(current)
  guix 45ca696
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 45ca6967ab7ac91b66e5b6fddfbc63317ff219a9
  nonguix 674d04a
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: 674d04a5fbd8689ab5ff27271a656f711fc77c54
$ guix show icecat
name: icecat
version: 91.11.0-guix0-preview1
outputs: out
systems: x86_64-linux
dependencies: alsa-lib@1.2.4 bzip2@1.0.8 cairo@1.16.0 clang@11.0.0
+ cups@2.3.3op2 dbus-glib@0.110 eudev@3.2.11 ffmpeg@4.4.2 font-dejavu@2.37
+ freetype@2.10.4 gdk-pixbuf@2.42.4 glib@2.70.2 gtk+@2.24.33 gtk+@3.24.30
+ hunspell@1.7.0 icu4c@69.1 libcanberra@0.30 libevent@2.1.12 libffi@3.3
+ libgnome@2.32.1 libjpeg-turbo@2.0.5 libnotify@0.7.9 libpng-apng@1.6.37
+ libvpx@1.11.0 libxcomposite@0.4.5 libxft@2.3.3 libxinerama@1.1.4
+ libxscrnsaver@1.2.3 libxt@1.2.1 llvm@11.0.0 m4@1.4.18 mesa@21.3.8
+ mit-krb5@1.19.2 nasm@2.15.05 node@10.24.1 pango@1.48.10 pciutils@3.7.0
+ perl@5.34.0 pixman@0.40.0 pkg-config@0.29.2 pulseaudio@15.0
+ python-wrapper@3.9.9 rust-cbindgen@0.19.0 rust@1.57.0 shared-mime-info@1.15
+ sqlite@3.36.0 unzip@6.0 which@2.21 yasm@1.3.0 zip@3.0 zlib@1.2.11
location: gnu/packages/gnuzilla.scm:556:2
homepage: https://www.gnu.org/software/gnuzilla/
license: MPL 2.0
synopsis: Entirely free browser derived from Mozilla Firefox  
description: IceCat is the GNU version of the Firefox browser.  It is entirely
+ free software, which does not recommend non-free plugins and addons.  It also
+ features built-in privacy-protecting features.  This package also includes the
+ `geckodriver' command, which can be useful for automated web testing.
+ 
+ WARNING: IceCat 91 has not yet been released by the upstream IceCat project.
+ This is a preview release, and does not currently meet the privacy-respecting
+ standards of the IceCat project.
```

 
 ---
 
 CC @ken107

**Comment by Kreyren** [comment]
Here:
![2022-07-17_08-26](https://user-images.githubusercontent.com/11302521/179386812-1a372d17-55a6-4cef-8c34-030dc314cfce.png)

Opening the URL i get just the extension window:
![2022-07-17_08-28](https://user-images.githubusercontent.com/11302521/179386833-db2e8e46-a5f1-481e-8722-2b1c444e39a9.png)

**Comment by montvid** [comment]
The same error on firefox for Android, can't grant permissions so can't use these voices.

**Comment by omega3** [comment]
I need to grand permissions also for piper voices when auto select is set.
https://github.com/ken107/read-aloud/issues/386#issuecomment-2082048043
After that it hangs a bit so I press stop and play again and after that it works ok. It opens a new tab (and pinned it somehow). As long as this tab is open it works ok. When I close this tab and want to listen another article / site it reopens this permissions tab again. I set grant access to browser activity but it doesn't change anything. It would be great to be able to set permissions permanently.

**Comment by soredake** [comment]
Same problem with GoogleStandart/Amazon/Microsoft voices, button are not clickable.

**Comment by ken107** [comment]
> I need to grand permissions also for piper voices when auto select is set. [#386 (comment)](https://github.com/ken107/read-aloud/issues/386#issuecomment-2082048043) After that it hangs a bit so I press stop and play again and after that it works ok. It opens a new tab (and pinned it somehow). As long as this tab is open it works ok. When I close this tab and want to listen another article / site it reopens this permissions tab again. I set grant access to browser activity but it doesn't change anything. It would be great to be able to set permissions permanently.

@omega3 On Firefox, newly opened tabs are not allowed to play audio, to prevent sites from autoplaying audio ads.  So unfortunately we have to grant that permission every time. I could not find a workaround.

**Comment by ken107** [comment]
> The same error on firefox for Android, can't grant permissions so can't use these voices.

31270bdf87d89ae8050d2aee997651b7ebe964e4 GoogleTranslate should work on Android now, please try again.

**Comment by ken107** [comment]
actually, 31270bdf87d89ae8050d2aee997651b7ebe964e4 fixed this issue, as the current method no longer requires the permissions.
