### ISSUE TITLE
Google Neural2 voices falling back to low-quality replacements

### ISSUE THREAD

**Issue by joliss** [ken107/read-aloud#280]
Google's ~~WaveNet and~~ Neural2 voices aren't working for me, instead falling back to low-quality replacements. Here's what I'm doing:

I copied my Google Cloud API key from here:

![Edit API key – APIs   Services – development – Google Cloud console 2022-08-01 15-24-55](https://user-images.githubusercontent.com/524783/182169957-adf263c6-004b-4ab0-a11f-4240e9d94004.png)

into the Custom Voices dialog like so:

<img width="501" alt="Extensions - Read Aloud: A Text to Speech Voice Reader 2022-08-01 15-26-29" src="https://user-images.githubusercontent.com/524783/182170191-2a7aeffb-f4cb-40e1-9ec7-edb29d5b9ff5.png">

Here's a recording of what my Neural2 and WaveNet voices sound like:

https://user-images.githubusercontent.com/524783/182174861-b9ee41b7-6031-4fbb-86bf-335e8bbdc150.mp4

There's no indication of any errors happening. This is what Read Aloud is printing to the console:

![Example Domain 2022-08-01 15-42-07](https://user-images.githubusercontent.com/524783/182175560-ddcccd40-57dd-4e05-ab7c-b9022f0d40bf.png)

Please let me know if there's anything I can do to help debug the problem!

**Comment by ken107** [comment]
Could you click on the Network tab in the Developer Console and see the details of the request to Google Cloud?  Are the right voiceName being sent?  Be sure to blackout the API key in the request URL

**Comment by joliss** [comment]
Thanks! Yes, you're correct that it *is* indeed the WaveNet voice. I thought for some reason it sounded worse than WaveNet. Sorry about that, I should've double-checked.

As for Neural2, these voices really do only show up once I add my API key in Custom Voices. Going by the [documentation](https://cloud.google.com/text-to-speech/docs/wavenet#neural2_voices_preview) they're basically next-gen WaveNet-like models. You can try them in the [demo](https://cloud.google.com/text-to-speech#section-2) if you change the "Voice type" to Neural2.

Inspecting the background page for Read Aloud, I see network requests to `text:synthesize` for WaveNet as expected, but no network requests at all for Neural2.

I wonder if it might be possible to support the Neural2 in Read Aloud? Note that they may need a [different endpoint](https://cloud.google.com/text-to-speech/docs/endpoints#text-to-speech-list-protocol).

**Comment by ken107** [comment]
I see, we'll have a look. Thanks

**Comment by ken107** [comment]
Thanks again for reporting the issue
