### ISSUE TITLE
Less robotic voices?

### ISSUE THREAD

**Issue by kaosine** [ken107/read-aloud#289]
Are there any of these voices that are less robotic sounding? I'm not having any luck finding one that works so I can focus on reading/listening to my text books. I'd just use cengage's builtin tool but it's just too fast on fast and normal is too slow(with no inbetween). Plus I'm not able to get the premium voices right now due to being in school and recovering from a surgery still.....

I'm on fedora using native firefox.

**Comment by ken107** [comment]
Please use this offline voice that will work reliably:
https://blog.readaloud.app/2020/09?m=1

**Comment by kaosine** [comment]
That looks like it's chrome only. I'm on firefox....

**Comment by ken107** [comment]
Sorry about that, Firefox's options are rather limited.  Please use the Premium voice by singing in, you'll get 1,000,000 free characters per month.  And if you run out, just email support@readaloud.app, we'll credit your account with more free characters.
