### ISSUE TITLE
Không thể đọc theo đoạn văn được bôi đen khi đọc file pdf online

### ISSUE THREAD

**Issue by trionline29** [ken107/read-aloud#29]
Em chào anh ạ,
Em hy vọng anh có thể cải thiện một chút về chức năng bôi đen đoạn văn trong file pdf hoặc file word thay vì chỉ đọc luôn hẳn nguyên trang , và có thể tự động chuyển đổi nhiều giọng đọc và tốc độ đọc khác nhau để người nghe có thể tập trung hơn khi đọc một cuốn sách dài ạ.
Thanks anh nhiều vì tool quá tuyệt vời ạ.

**Comment by ken107** [comment]
Bôi đen PDF và Word OK rồi đó bạn.

Còn tự động chuyển giọng đọc, ý kiến này hay đó, tức là đổi giọng khi đọc cái mẫu đối thoại.  Tuy nhiên chắc không thực hiện được vì nhiều đoạn đối thoại không rõ ràng ai đang nói câu nào.  Mấy chức năng này đòi hỏi 1 chút kỹ thuật thông minh nhân tạo, nói chung là khá phức tạp.
