### ISSUE TITLE
AWS Polly voices not working on Win11/firefox

### ISSUE THREAD

**Issue by GitToby** [ken107/read-aloud#291]
When trying to read any page there is no response until eventually there is an error banner, such as below appearing. I suspect this is likely a Firefox API issue given my [googling of the error](https://bugzilla.mozilla.org/show_bug.cgi?id=1655614).

![image](https://user-images.githubusercontent.com/9465529/190974692-a9b772f6-26ef-469b-ae17-490d2cec3936.png)

```
The media resource indicated by the src attribute or assigned media provider object was not suitable
```

**Comment by ken107** [comment]
Could you go to these two sites and see whether your Firefox installation can play either MP3 or OGG Vorbis?
https://file-examples.com/index.php/sample-audio-files/sample-ogg-download/
https://file-examples.com/index.php/sample-audio-files/sample-mp3-download/

Many Firefox installations, particular Linux, don't support MP3 playback.  So I had switched to OGG Vorbis some releases ago.  I think OGG should be supported by all Firefox versions, but may be not.  Which version of Read Aloud, Firefox, and which OS are you using?

**Comment by GitToby** [comment]
This has since worked itself out; I assume through an update but I wasn't really on it with checking. Apologies.
