### ISSUE TITLE
Added Indian English Kajal Voice  +neural voice

### ISSUE THREAD

**Issue by prakhs123** [ken107/read-aloud#297]
https://github.com/ken107/read-aloud/pull/296 --was not working

self explanatory

Edit: added bug report in AWS, https://repost.aws/questions/QUG9SUOC97Q-W8yTpvCN-OSw/kajal-is-not-added-as-a-valid-voice-id-in-amazon-polly-api-action-synthesize-speech

**Comment by prakhs123** [comment]
https://support.readaloud.app/read-aloud/list-voices/amazon
doesn't list Kajal as +neural voice

**Comment by ken107** [comment]
That has been fixed now, could you please try again?
