### ISSUE TITLE
Shortcut keys for Pause/Stop/Next/Prev

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#30]
Defaults:
Pause/Resume:  ALT-P
Stop:  ALT-S
FF:  ALT->
RW:  ALT-<

Add link bottom of options page:
[chrome://extensions/configureCommands](Edit shortcut keys)

**Comment by ken107** [comment]
f601f36

**Comment by ajhsu** [comment]
The new hotkey feature it just AWESOME to make it even more easier than a button clicking! Thanks @ken107 , love it!

**Comment by ken107** [comment]
Yea, I love it too, I no longer like to use the mouse now.
