### ISSUE TITLE
Switch between pre-selected voices easily

### ISSUE THREAD

**Issue by nagyistv** [ken107/read-aloud#303]
Hi!

First of all, thanks for this great extension, I use it all the time. I use it on English pages and even on pages written in my native language. So I have to change the voice between the 2 languages quite often. 
I think something like a switch button on the options page or a new section in the context menu would be a useful feature to make this process more convenient.

**Comment by ken107** [comment]
Could you go to Options and click on the Pencil icon next to the Voice dropdown?  It will take you to the Languages page where you can select your preferred voice for each language.  Then on the options page, select "Auto select" for voice and it will automatically use your preferred voices.

**Comment by nagyistv** [comment]
Ohh... I didn't know about it. That's even better. Thanks! :)
