### ISSUE TITLE
No listed options for Google Studio voices

### ISSUE THREAD

**Issue by DavidMetcalfe** [ken107/read-aloud#304]
It appears a new option has been added to Google's premium Text-To-Speech voices called [Studio voices](https://cloud.google.com/text-to-speech/docs/wavenet#studio_voices).

Per Google's description: "The Text-to-Speech API provides Studio voices. This voice type is designed specifically for use with long-form texts such as narration, news reading, and so on."

Please add support for these as they seem to be right in the area of what Read Aloud is best suited for.

**Comment by ken107** [comment]
We're hiding these voices because they're quite [expensive](https://cloud.google.com/text-to-speech/pricing) (160 USD per million characters).  These are really intended for commercial purposes, such as business marketing, video voiceover, etc., rather than for generic TTS purposes.

We're waiting for AI-based text-to-speech technology to become more ubiquitous and more affordable.  That day should come very soon, so please stay tuned.

**Comment by franciscoabenza** [comment]
I want them to be there too. So much that I ask chatgpt to implement them
I am too lazy to PR though

`function getAudioUrl(text, voice, pitch) {
    assert(text && voice);
    var voiceName, endpoint;
    if (voice.type === "Studio") {
        // For Studio voices
        voiceName = voice.lang + "-Studio-" + voice.gender;
        endpoint = "texttospeech.googleapis.com"; // Assuming Studio voices use this endpoint
    } else {
        // For other voices (existing logic)
        var matches = voice.voiceName.match(/^Google(\w+) .* \((\w+)\)$/);
        voiceName = voice.lang + "-" + matches[1] + "-" + matches[2][0];
        endpoint = matches[1] == "Neural2" ? "us-central1-texttospeech.googleapis.com" : "texttospeech.googleapis.com";
    }
    
    return getSettings(["gcpCreds", "gcpToken"])
      .then(function(settings) {
        var postData = {
          input: {
            text: text
          },
          voice: {
            languageCode: voice.lang,
            name: voiceName
          },
          audioConfig: {
            audioEncoding: "OGG_OPUS",
            pitch: ((pitch || 1) -1) *20
          }
        }
        // Rest of the function remains the same...
    });
}
`
