### ISSUE TITLE
[[ Feature request ]]: Add support to speak parts of text in different languages.

### ISSUE THREAD

**Issue by ccuser44** [ken107/read-aloud#307]
A feature should be added which would allow you to speak a part of the websites text with one language and parts of with another language.

What this feature should be like:

- You should also have an easy way of doing this and have character percise control over at which language a text is read in (via the text interface).

- Also there should be a way to easily select which HTML elements are read in what language by clicking them. (_To make it easy to use_)

- It should also be able to seemlessly switch between languages while reading when it starts reading text in a different language. (_Instead of the user having to do this manually, because that would defeat it's purpose._)

- There should also be a feature which would auto detect the language for the text based on the HTML `lang` attribute. (_Different HTML elements can be under different `lang` attributes. Also descendants HTML elements iherit their anchestors `lang` attribute._)

Why this should be added:

This would probably be one of the greatest features that the extension could have and it would open up a lot of possibilities.

For example if there are websites which use multiple languages it could make reading them a lot easier.

Also it would make repetetive lisening to multi-lingual content much much easier and would be a huge quality of life improvement.

**Comment by ccuser44** [comment]
Bump

**Comment by ken107** [comment]
Currently you can select text to read aloud, and if voice is set to "Auto select", RA will detect language and use the appropriate voice.  This is as far as we'll do to support multiple languages on the same page.
