### ISSUE TITLE
Native voices on MacOS need to show the language

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#319]
Also it speaks too fast by default, can we slow it down by default?
how to know it is MacOS native voice?

**Comment by vamuscari** [comment]
Hey! so I was having a similar issue and came here to look into it. 

## Rate

This seems to be an issue between chromium and mac OS. If I go to [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/rate) on both chrome and safari, then play the example. Safari plays back at a slower(probably correct) rate where chrome plays back super fast. 

## Native voice

My guess for knowing the native voice would be to first know if the device is on a mac. Then from the list of voices check for [localService](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/localService). I believe these voice are a direct reflection of the system voice. Zoe(premium) will show up if downloaded but I don't see any version of siri.

**Comment by ken107** [comment]
Thank you for the info!
