### ISSUE TITLE
Đọc văn bản song ngữ

### ISSUE THREAD

**Issue by trionline1234** [ken107/read-aloud#320]
Anh có thể mở rộng đọc văn bản song ngữ, tự động nhận dạng ngôn ngữ từng câu được không ạ ?
Vì hiện tại đã có extension dịch website thành dạng song ngữ chẳng hạn như https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh hoặc các báo song ngữ.
Sẽ rất cần thiết cho người học ngoại ngữ khi chức năng này được hoàn thiện ạ, nhất  là khi câu tiếng Anh được đọc đi đọc lại nhiều lần, vừa luyện đọc song song với luyện nghe.

**Comment by ken107** [comment]
duplicate of #324
