### ISSUE TITLE
Extension isn't running in background

### ISSUE THREAD

**Issue by allmightyasian** [ken107/read-aloud#327]
So im unable to use read aloud in background, like i was able to before srcnext updates, in kiwi browser,
Is there's a way to fix this, if not please do something about it,
It isn't running in, locked screen, when i turn screen off

**Comment by ken107** [comment]
Could you confirm you are using Read Aloud for Firefox on Android?

**Comment by allmightyasian** [comment]
> 

In android kiwi browser
