### ISSUE TITLE
German voice

### ISSUE THREAD

**Issue by jjsarton** [ken107/read-aloud#33]
The speech rate (speed) must be increased for the German language (Google Deutsch). If this i not done some words will not be spoken out.
For the text:

Das sind beispielsweise Hinweise auf Gedenktage, Jahrestage, ein passendes Gedicht zu einem bestimmten Anlass oder sonstige interessante Begebenheiten, die nicht unmittelbar mit Göcklingen in Verbindung stehen. Wir werden uns aber weiter bemühen, Sie originell zu unterrichten.

Speaking stop at "Sie ori". "ginell zu unterrichten." is not spoken.

**Comment by ken107** [comment]
Thank you, I understand this problem.  Will fix soon.

**Comment by ken107** [comment]
This is fixed in the latest version (1.2.10).  Please let me know if you still experience the issue.  Thank you.

**Comment by jjsarton** [comment]
The fix seem to be OK, I have performed a short test without problem. Reducing the chunk size what probably the solution. The problems occurred only with the default German voice.

**Comment by ken107** [comment]
Yea, built-in Google voices have this problem where speech is limited to 15 seconds.  So we have to chop an article up into small chunks.  For Latin languages I set a chunk size of 36 words, which appears to work fine for English, France, etc.  But German words are a little longer, so need smaller chunk size.
