### ISSUE TITLE
Dự án cộng đồng, audiobook song ngữ

### ISSUE THREAD

**Issue by trionline29** [ken107/read-aloud#34]
Chào anh Ken107, 
Tụi em hiện tại đang làm các dự cộng đồng phổ cập Ielts cho mọi người và xa hơn nữa - giai đoạn dịch thuật toàn bộ sách luyện thi Ielts Cambridge Reading và Listeing hiện đã hoàn thành, và đang trong giai đoạn sản xuất audio song ngữ để mọi người có thể học dễ dàng học trong mọi hoàn cảnh.
Và đây là link một demo dự án tụi em đang thực hiện ạ:
https://www.facebook.com/permalink.php?story_fbid=214453535779945&id=100016459000518
https://sites.google.com/site/learnvocabinieltsreading/home/cambridge-ielts-12/collecting-as-a-hobby

Tình cờ biết được Extension của anh trên github, nên em nảy ra ý tưởng mời anh hợp tác cùng dự án để dự án có thể mở rộng ra cho nhiều lĩnh vực, giúp ích cho người Việt Nam ạ.

Ý tưởng của em: 
+ Tool sẽ tự động đọc lần lượt các cụm câu Anh-Việt luân phiên
+ Trong các câu tiếng Việt, các collocation sẽ được thay thế bằng cụm từ tiếng Anh.
+ Xuất file audio song ngữ/ chuyện chêm ra file .mp3.
+ Tự động chọn ngẫu nhiên một vài giọng đọc định sẵn trong một bài Reading, để giúp người học dễ ghi nhớ hơn.

_ Vướng mắc còn lại sẽ khó để tool nhận dạng được liên tiếp tiếng Anh và tiếng Việt, nên em xin đưa ra giải pháp:
+ Đối với bài Reading Anh-Việt,                      ---> sẽ quy định số câu trong 1 đoạn.
+ Đối với chuyện chêm các cụm từ Anh-Việt,  --->dùng dấu [ ] để giới hạn cho tools biết đâu là các cụm từ Anh - Việt để thay đổi.

Với những gì mà dự án đã thực hiện, em tin rằng dự án sẽ phát triển mạnh và xa hơn nhiều nếu được sự hỗ trợ quý báu của anh, không chỉ là đối với việc học Ielts mà còn trên tiếng Anh cho các lĩnh vực chuyên nghành khác nhau. Một tương lai hơn 90 triệu người Việt Nam thành thạo tiếng Anh sớm thành hiện thực ạ.

Chân thành cảm ơn anh đã dành thời gian đọc bài viết của em, 
và em xin chúc anh năm mới nhiều sức khỏe và nhiều thuận lợi hơn trong sự nghiệp của mình.

**Comment by ken107** [comment]
Xin chào bạn, dự án của bạn rất có ý nghĩa.  Mình sẽ giúp bạn 1 tay.

Việc nhận dạng Anh/Viet thì có thể hoàn toàn tự động hóa, không cần thêm ký hiệu.  Chữ tiếng Anh và tiếng Việt khác nhau khá nhiều, có thể dựa vào một sỗ luật đơn giản:
- Chữ tiếng Việt lúc nào cũng gồm 1 phụ âm, 1 nguyên âm, sau đó thêm 1 phụ âm.
- Số phụ âm và nguyên âm tiếng Việt rất giới hạn

Mình có thể tạo 1 script để bạn embed vào trang web trên, giống như ở đây: https://ken107.github.io/read-aloud
Chỉ khác cái là nó sẽ tự động nhận dạng tiếng Anh hoặc Việt rồi đọc đúng giọng.

Tuy nhiên hiện tại mình đang rất bận rộn, chưa thể giành thời gian cho việc này được.

**Comment by trionline29** [comment]
Dạ em cảm ơn anh đã phản hồi,

Em nghĩ nếu có thể tích hợp vào extension với chệ độ tự động nhận dạng song ngữ thì có có lẽ tiện hơn, toàn bộ file đọc tụi em sẽ xuất ra file mp3 và upload lên youtube ạ.

Một lần nữa, xin cảm ơn anh đã nhiệt tình ủng hộ cho dự án ạ.
Chúc anh nhiều năng lượng và sức khỏe dồi dào ạ.
