### ISSUE TITLE
Robotic voices on Firefox, works perfectly in Chrome...

### ISSUE THREAD

**Issue by RafeedArian99** [ken107/read-aloud#340]
I'm on Fedora 38.

All the voices on Firefox are robotic, while all the voices on Chrome are working perfectly. The options appear to be slightly different as well.

**Comment by ken107** [comment]
Chrome comes with a set of decent quality tts voices built into the browser, i.e. the Google US English and similar voices. Firefox doesn't. The default tts voices on FF are quite low quality.

It's not something that we can do something about. You can go to options and select other voices like the Read Aloud Generic Voice, that one we provide as an option, which should work fine.

**Comment by RafeedArian99** [comment]
Gotcha, thanks!

I can't seem to find the "Generic Voice", but Google Translate voice is good enough.

**Comment by farid220** [comment]
> Chrome comes with a set of decent quality tts voices built into the browser, i.e. the Google US English and similar voices. Firefox doesn't. The default tts voices on FF are quite low quality.
> 
> It's not something that we can do something about. You can go to options and select other voices like the Read Aloud Generic Voice, that one we provide as an option, which should work fine.

I have the same Issue in my CentOS 9 Stream. I know all voice are robotic to some extent but this one is extremely robotic and I'm sure it is not normal because I've used it on Windows too and I don't experience such a robotic voice.

Please check it and tell us if we can be as of help by providing necessary logs.

Thank you

**Comment by ken107** [comment]
You can go here to test the voices available on your system https://ttstool.com/soundboard.html . Firefox on Windows has poor quality voices. Firefox on Linux has even worse voices. This is not something that the extension controls.
