### ISSUE TITLE
Can't use google translate voice 

### ISSUE THREAD

**Issue by asecino1999** [ken107/read-aloud#345]
i'm using firefox on ubuntu . 
i used this extension months ago and it worked fine   with the voice of google translate voice  . 
but now it only uses google translate voice the first time ( after opening firefox )  then  it only uses the robotic voice of Firefox .

**Comment by joejac** [comment]
Hello, same is happening to me, before was working fine but now the voice is always robotic no matter which voice do I select, is not possible to understand, can it be repaired please?.
I am using Firefox on MX Linux (Debian derivative)
Thank you

**Comment by brmassa** [comment]
It's driving me nuts. same problem here. Sometimes restarting Firefox fixes the issue. Or copy-paste to Chrome to just use Read Aloud

+1

**Comment by ken107** [comment]
The GoogleTranslate voices may stop working if you use it for too long (about an hour).

GoogleTranslate text-to-speech service has seen too much usage lately.  Because it was designed to support the translate.google.com website, not for use by everyone to read large amounts of text

**Comment by brmassa** [comment]
@ken107 sarsa, the problem is not in Google translate voice per se, but the sudden change to a robotic voice. It seems (to be confirmed) the the addon cannot find a suitable voice and go for a default one. It happens on Linux only

**Comment by ken107** [comment]
Yes, since we know GoogleTranslate voices may stop working at some point, at Google's discretion, since the beginning we have included code to fall back to other voices.

The default voices on FF are unfortunately quite poor quality. You might want to choose the ReadAloud Generic Voice, or install Piper voices.

**Comment by brmassa** [comment]
ok. Understood. The only doubt I have is: why it happens only on Linux? I've never experienced this on Windows machines...
