### ISSUE TITLE
Personal profiles feature

### ISSUE THREAD

**Issue by FajnB** [ken107/read-aloud#346]
Hi, I have been using this extension/add-on for more than three years now.
It have saved me countless times. So thank you for creating it! I appreciate it.

## The idea
In this thread I want to propose an idea of personal profiles feature.

What do I mean by that? It is simple. Just have the ability for user to create/save a specific profile, which would contain the language/specific synthesiser, speech speed and, in synthesisers which support it, the pitch.
User can save these setting under their own profile to which they'll give a name.

There could be a drop down menu with these profiles.

## The explanation
Hear me out.
I my self am fluent in several languages, but not equally across them.
So let's assume that there are two articles in two different languages. In this case for ex. English and Czech lang respectively.
I want them to be read as fast as I can comfortably understand. So what I do is I set up the English one to the speed about 2.3x. This is absolutely perfect for me. In fact I want this to be at this speed every time I come across English text to be read. Now I switch to the Czech article. But the speed is too much for me. :( Well I tinker around and find the perfect speed for me in this language, which is around 2x.

I think you see the problem. Users now have to constantly change the speed depending on the language.

Also as mentioned to me by my friend, who also uses Read Aloud, he sometimes uses this add-on to read a book. Some sort of DIY audio book. And he likes it to be read at much slower speed, maybe around 1.3x. So now he must change the speed precisely every time he listens to different things. Note: He is that kind of person who uses 1.85x and 1.283x settings, but the point still stands.

#
In my personal opinion, yes this is probably a power-feature, but I am almost certain that a lot of people would appreciate it and love it.

What do you think?

## Some nice to haves
_As a unnecessary bonus, there could be a export/import option so that people with multiple PCs can have their profiles always with them if the wish so.
And maybe a shortcut key for switching between the profiles._

**Comment by ken107** [comment]
If can develop an intutive UI/UX for this, it would be nice to have.  Solves #79

**Comment by ken107** [comment]
Speed is set individually for each voice now.  We'll not add profiles since it entails signficant new UIs.

**Comment by ken107** [comment]
Speed is set individually for each voice now.  We'll not add profiles since it entails signficant new UIs.
