### ISSUE TITLE
Google voices not working in Firefox

### ISSUE THREAD

**Issue by ziroc** [ken107/read-aloud#347]
Come on guys, this has been reported multiple times. At least for half an year.

I think it happens when the user has the video autoplay disabled.

**Comment by ken107** [comment]
Which voice are you referring to?  The "Google US English" and similar voices are only available on Chrome.

**Comment by ziroc** [comment]
Sorry I was annoyed. Every Google voice is not working. 
I found the problem - I had audio/video autoplay disabled.

 When I enabled it - works. But I cannot use the browser like this.

**Comment by ziroc** [comment]
Further investigation - if I disable autoplay and add exception for the site I want to use read-aloud, it is again not working. It seems some other domain has to be in the exception list.
![image](https://github.com/ken107/read-aloud/assets/37216225/f8c23e73-0102-46e5-b465-6e00eafac974)

**Comment by destgub** [comment]
I have been using Google Tanslate vice on Firefox under Windows for months and for about a week they no longer worked. But I solved it by removing the extension, restarting Firefox and reinstalling the extension.  (remember to grant the permissions required by the addon)
