### ISSUE TITLE
Service doesn't start on selecting it

### ISSUE THREAD

**Issue by bheeshmpita** [ken107/read-aloud#349]
From past month or two, i am facing this issue where the service doesnt starts if there is no read aloud tab among my other tabs. The only way to get that tab is to select some text from webpage and from the context menu choose the 'Read aloud selected text'. When this tab appears everything works as before but there is short-lived till the tab closes automatically after few minutes of non-usage which can't be bypassed even by pinning the tab.

**Comment by ken107** [comment]
> i am facing this issue where the service doesnt starts
You say the service doesn't start, what action do you take to start the service?

**Comment by bheeshmpita** [comment]
> what action do you take to start the service

i generally select any word from the webpage to be read and right click and then choose 'Read aloud selected text'. It will get the service started and now deselect the word and use the service as usual, then it works fine.
If it still doesnt get started then i close the popup window of the read aloud and repeat this process and this works everytime.

**Comment by ken107** [comment]
So what's the problem you're experiencing now? What button do you click and what's supposed to happen but doesn't happen?

**Comment by bheeshmpita** [comment]
> So what's the problem you're experiencing now?

the problem i face is after clicking the extension button the read aloud separate window appears but it remains blank ie no text appears that needs to be read.

>  What button do you click 

Amongst the extension buttons, the one that has your logo (the loudspeaker in black and orange)

> what's supposed to happen but doesn't happen?

As the read aloud window appears (i have selected separate window instead of popup in its options) the text to be read should appear and the reading voice should initiate and gradually the entire text to be read but only the blank window appears.

I have been using this amazing service from past couple of years without any issue so i think i know how to use this service and not making any amateur mistake.

**Comment by ken107** [comment]
Do you see any red error messages?  And what is the URL of the web page you're trying to read aloud?
