### ISSUE TITLE
Ability to vary languages, speed et al not available under Chrome OS

### ISSUE THREAD

**Issue by michael-mayes** [ken107/read-aloud#35]
Hi

This extension was working well under Chrome on my old Windows 10 laptop, but under Chrome OS 63 on my Chromebook it is no longer allowing selection between voices or saving changes to pitch or volume

All I am seeing in the options is as the screenshot below

I did manage to get the UK English Google voice to work with another screenreader, but that extension was otherwise pretty terrible

Any suggestions for getting this extension working again for me?

![screenshot 2018-01-26 at 23 49 02](https://user-images.githubusercontent.com/11037231/35465418-b27431c2-02f3-11e8-909f-54f152265c09.png)

**Comment by ken107** [comment]
Would it be possible for me to remote desktop into your computer to diagnose the issue?

**Comment by chew-z** [comment]
It works fine for me on ChromeOS 64.4.36 - Neverware build.
