### ISSUE TITLE
Google Docs Workspace version no longer works

### ISSUE THREAD

**Issue by KosmoKhaos** [ken107/read-aloud#350]
Hello, I just wanted to report that the version you have to download via workspace to have this app in google docs no longer works. It seems that the file has been deleted from google drive. Hope it gets fixed soon because this is the only TTS app that works for google docs on firefox. And I love its pitch and speed options.

**Comment by ken107** [comment]
Thank you, I'm working on it, please allow a few days.

**Comment by ken107** [comment]
The addon is back, please reinstall.  Thanks

**Comment by KosmoKhaos** [comment]
> The addon is back, please reinstall. Thanks

Thank you so much! It works again. Saved me a lot of stress! Thank you!
