### ISSUE TITLE
Options to enable Google Studio voices

### ISSUE THREAD

**Issue by stephen-soltesz** [ken107/read-aloud#351]
Hello, @ken107, thank you for your commitment to developing and making ReadAloud available. I use it almost every day.

If I understand correctly, the rationale to [not enable Google Studio voices](https://github.com/ken107/read-aloud/issues/304#issuecomment-1522923746) in ReadAloud right now are: 

- Google Studio voices are more expensive
- These (or something equally good) should be more affordable in the future

Before the voice costs are reduced, are there any conditions under which you would consider allowing ReadAloud users to select Google Studio voices in the official release of ReadAloud sooner?

For my use cases, the quality of the Google Studio voices is worth the increased cost (they're really excellent). I suspect other ReadAloud users already using the premium voices would also welcome the option (even if it's at an increased cost).

In a local build, using Chrome extensions developer mode, I'm able to [hard code the voice name](https://github.com/ken107/read-aloud/blob/dfb01f02ce04913f351654ac3baf30c621922fa4/js/tts-engines.js#L791), which basically meets my needs.

- e.g. `var voiceName = "en-US-Studio-Q";`

But, this is a hack and not available to anyone else easily.

If code changes were prepared by me or another contributor, can you imagine accepting PRs that make Google Studio voices available? Could you imagine any of these working?

- Create a checkbox associated with the GCP API key configuration option reserved only for Google Studio voices. This could include a note warning about costs. Users would explicitly opt into these voices.
- Create an "advanced" option to specify a literal voice name, which would override any other options. e.g. text box with a string "en-US-Studio-Q", etc.
- Commission the feature, funding development time through gofundme or similar? What amount would make it worthwhile?

Or, is there another way that might be simpler than what I can imagine and that you would consider accepting changes to support?

Thank you!

**Comment by ken107** [comment]
The risk is only in users accidentally running up a large bill. They may forget they are using a Studio voice, and then read a bunch of articles, running up a bill of 50 dollars, for example. That may not be much to you, but a significant bill for most people. These voices are 10 times more expensive than the next options, they are meant for commercial use by enterprises.

**Comment by ken107** [comment]
Okay, I will accept a PR adding a checkbox in the newly added "Advanced Options" page.  The `GoogleWavenetTtsEngine` should filter out Studio voices by default, and the filter can be disabled by the checkbox.

Currently I'm filtering out Studio voices from the server side.  Once the advanced option is in place, I can remove the filter.

**Comment by nhan000** [comment]
Hi, after register the API key, I can see many GoogleNeural2 and GoogleWavenet voices, but no Studio voices. Am I missing something? Thank you!

**Comment by ken107** [comment]
Sorry I forgot to remove the filter on the server side.  The Studio voices should appear now.  Thanks for letting me know.  By the way, make sure you know many characters you're consuming and monitor the daily cost in the Google Cloud Console.

**Comment by nhan000** [comment]
I still don't see the Google Studio voices? I guess I need to wait for an update from the Chrome Web Store?

Btw, how can I check for the characters/bytes I've consumed? What command do I run in the console? I've click everywhere in the Billing section, but I couldn't find my consumption/billing info. I just registered my GCP account so I have $300 credit so I'm not too worried about it yet but in the future I definitely need to pay close attention to my usage.

**Comment by ken107** [comment]
Please go to "Enable Custom Voices", reenter your GCP API key, check the "Enable Studio voices" box, click "Save". The status should show "Google Wavenet and Studio voices are enabled".  Then open Options and look for the GoogleStudio voices, which comes after GoogleStandard voices.

This is currently the only way to check how many characters you have used at the end of the day:
https://stackoverflow.com/questions/63938975/google-cloud-text-to-speech-character-counts

Be careful with that $300 credit, I'm not sure how it is applied but it's only reducing a few dollars off my bill so far.  That credit applies only to specific spending or something like that, I'm not sure.
