### ISSUE TITLE
Phonic rules

### ISSUE THREAD

**Issue by starsor** [ken107/read-aloud#352]
The reader keeps pronouncing "caregiver" as "care - jīver". There are exceptions to phonetic English words.  Give, giver(s), gift are some of those exceptions.

**Comment by ken107** [comment]
This depends on the voice you select.  The extension only gathers the text and hand it to the voice engine.  The extension doesn't control how the different voice engines interpret the text and how they pronunce things.  You can try picking other voices that will work better for you.
