### ISSUE TITLE
Feature Request: Have number indicator for pitch setting.

### ISSUE THREAD

**Issue by nhan000** [ken107/read-aloud#362]
Currently only speed has a toggle to show the number. It'd be great to have the same thing for Pitch. Best is to show the number next to the slider.
![image](https://github.com/ken107/read-aloud/assets/85216095/9fc688e7-7a03-4e5f-bad7-49b657ba28c0)

This issue https://github.com/ken107/read-aloud/issues/331 would solves all of the above, but until then, I'd do with a toggle for the pitch setting. Thank you!

**Comment by ken107** [comment]
The speed setting can be beyond the range allowed by the slider, hence the need for an editable.  The pitch setting does not require this option, which adds complexity to the UI, something we try to minimize.
