### ISSUE TITLE
Sever Return 429

### ISSUE THREAD

**Issue by beomuzik** [ken107/read-aloud#363]
từ ngày 01/12/2023 cứ nghe được tầm hơn 10 phút là bị lỗi sever 429 
![Untitled](https://github.com/ken107/read-aloud/assets/153387076/52aa8635-b0d7-4427-a859-05579af240a0)

**Comment by ken107** [comment]
Bạn xài nhiều quá nên bị GoogleTranslate chặn.  Nếu nghe hơn 1 tiếng đồng hồ liên tục sẽ bị chặn, vì làm quá tải hệ thống của họ.  Hãy sử dụng giọng Piper mới up.
