### ISSUE TITLE
Feature Request: Adjust(able) pause length between sentences

### ISSUE THREAD

**Issue by GuardianMatrix** [ken107/read-aloud#364]
Using the chrome extension at 1.25x reading speed, the pauses between sentences seem unnaturally long and, at least to my own perception, disrupts the flow of narration.

Is it possible to have an option that sets the length of pause to scale inversely with reading speed? Or even make it user adjustable?

Thanks for this extension btw. Great work.

**Comment by ken107** [comment]
For most of the cloud voices, the pause between sentences/paragraphs are controlled by us, and change proportionally to the reading speed.  The other voices such as the "Google US English" voice and those provided by the browser have built-in pauses that we don't control; we are reading them immediately one after another.  Unfortunately at higher reading speed, these built-in pauses do not scale correctly, resulting in unnatural pauses.

Which voice are you using?  Or are you using "auto select"?

**Comment by GuardianMatrix** [comment]
Yep, 'auto select'. Thanks for clarifying what's happening. Unfortunate indeed. I'll look into cloud voices.
