### ISSUE TITLE
Voice cuts out when reading

### ISSUE THREAD

**Issue by plasmadice** [ken107/read-aloud#38]
Using Chrome:  Voice Amazon US Salli

On latest version, when selecting a block of text to read the voice will cut out after a certain amount of time spent reading.

**Comment by ken107** [comment]
Could you provide a link where you encountered this issue?  How much text did you select?  How many times did this happen for you?

**Comment by plasmadice** [comment]
https://www.robinwieruch.de/complete-firebase-authentication-react-tutorial/ 

Some of the first paragraphs in that article. I'd select the whole paragraph and it would cut out about halfway. I don't have this issue on the older version of the extension.

**Comment by ken107** [comment]
Is it happening right now?  I just tried and have no problem at all!  Using Amazon Salli.

I selected the first paragraph, reads entirely through.  Then I select the second paragraph, reads entirety.  Same for third paragraph.  Then I select all 3 paragraphs and it reads the entire thing without problem.

**Comment by plasmadice** [comment]
It's working right now. I guess I just needed to remove and add the extension again. ¯\_(ツ)_/¯ Thanks!
