### ISSUE TITLE
[feature request] pre-define language for specific site

### ISSUE THREAD

**Issue by omega3** [ken107/read-aloud#386]
Allow to per-define default language by setting voice to certain sites, for example:
English for https://www.bbc.com/
Polish for https://www.polsatnews.pl

I started using Piper voices and language detection doesn't work. So, some configuration file would be a great solution.

This would allow not to change options every time user wants to view sites in different languages. Usually users frequently visit the same favorite sites at least for reading news.

**Comment by ken107** [comment]
Please try:
- Go to options and set Voice to "Auto select"
- Click on the Filter icon to the left of the Voice dropdown to open Language settings
- Then toggle the English and Polish checkboxes and pick your preferred Piper voice for each language

In "Auto select" mode, Read Aloud will detect the language of the article, then choose the Preferred voice for that language that you have set.

**Comment by omega3** [comment]
It works with Read aloud generic voice but it doesn't work with Piper voices.

**Comment by omega3** [comment]
I reinstalled and switching voices works ok. Perhaps I have chosen only one voice per language, while previously I had two voices or more per language downloaded. 
But now it opens new tab and
https://i.imgur.com/KR82Tt3.png
