### ISSUE TITLE
Piper External

### ISSUE THREAD

**Issue by MrChuw** [ken107/read-aloud#389]
Option to use piper externally, such as that provided by [LinuxServer](https://docs.linuxserver.io/images/docker-piper/), which runs in a docker container using the Wyoming protocol. Thus giving the possibility of offloading the generation to another machine.

... so, if it supported the Wyoming protocol it would already support several other types of voice generation from what I can see.

**Comment by ken107** [comment]
Please direct this to the official Piper repo
