### ISSUE TITLE
When an article mixed with two languages

### ISSUE THREAD

**Issue by qins** [ken107/read-aloud#39]
Nice app!

But can not read chinese words when select english reader, and can not read english words when select Chinese.

Is there an option to read an article with two language words?

**Comment by ken107** [comment]
Hello, can you try one of the Microsoft Chinese voices, those should be able to read both Chinese & English.  Also try one of the Amazon Chinese voices.

**Comment by qins** [comment]
Thank you for your quick reply.
Really THE BEST Text Reader In HISTORY.

**Comment by ken107** [comment]
Thanks! Indeed

**Comment by qins** [comment]
Microsoft Chinese voices are able to read high quality Chinese and low quality English.
Is there a way to enjoy both high quality voices?

**Comment by ken107** [comment]
Unfortunately it's quite difficult to implement.  Not only have to detect language on a word-by-word basis, which cannot be done generally because language detection requires at least a paragraph of text for reliable detection.  Even if we manage to do that, switching TTS engine in mid-sentence could introduce longer pauses.

Sorry I'm afraid it can't be done at the moment.  Please try the few Chinese voices available and pick the one that sounds best.

**Comment by qins** [comment]
How about merge both high quality languages into one?

**Comment by ken107** [comment]
That will have to be done by the voice engines, which is out of my control.  We're only using voice engines already available provided by Google, Amazon, etc.  Thanks

**Comment by HackersCardgame** [comment]
> Unfortunately it's quite difficult to implement. Not only have to detect language on a word-by-word basis, which cannot be done generally because language detection requires at least a paragraph of text for reliable detection. Even if we manage to do that, switching TTS engine in mid-sentence could introduce longer pauses.
> 
> Sorry I'm afraid it can't be done at the moment. Please try the few Chinese voices available and pick the one that sounds best.

Hello

first TNX for this app, i use it thankful every day.

The problem "detecting language on a by word basis" is maybe not that complicated for bigger quotations

PseudoCode:
IF
(a sentence with more than 5 Words or something in qotes is 60% words from the Enlgish dictionary and only 40% german)

then 

switch language for this sentance / quatation from initially detected Language (eg German) to English 

FI
