### ISSUE TITLE
Read aloud addon for Google Workspace for education asking for logon

### ISSUE THREAD

**Issue by Gbtolvudeild** [ken107/read-aloud#393]
Hi, 
We have read aloud installed to our Google Workspace for education through the Admin console.   Yesterday we could not use Read aloud - it asks for a logon when we try to use premium voices, and even if you insert your credentials it still reverts to ask for logon again.   Please sign in to use Premium Voice -  I found the same issue here:  https://github.com/ken107/read-aloud/issues/199

![readaloud](https://github.com/ken107/read-aloud/assets/167420531/6feb594f-f7c8-4aa9-931a-60fb2a6e3443)

**Comment by ken107** [comment]
Please click on the Gear icon to the right of the Play icon. Then in the Options page, select one of the many non-Premium voices.  You're in an educational setting, so you probably don't want to use the Premium voices.

**Comment by Gbtolvudeild** [comment]
Hi,  we really need the premium voices - we use the Icelandic Dora and Karl - the other voices are not as good as those.  They used to work for us until yesterday.

**Comment by ken107** [comment]
By "inserting credentials", do you mean entering email and password into the login form?  What happens when you enter your credentials and press Sign in?  What error message do you get?

**Comment by Gbtolvudeild** [comment]
![readvilla](https://github.com/ken107/read-aloud/assets/167420531/d5e40ea9-4ff0-4300-9e2d-f4a4c2c997f7)
yes, sign in with my email and pass for my organization.

**Comment by ken107** [comment]
Okay, your email probably is invalid.  Can you try the "forgot password"?  You can send your emall address to support@readaloud.app and I can look it up.

**Comment by Gbtolvudeild** [comment]
I don't think that is the problem,  we have hundreds of users in our Google Workspace for Education and everyone has the same problem.

Can you tell me if Read Aloud needs to have third party cookies allowed to be able to work?   We are blocking third party cookies in our Google Workspace.
________________________________

**Comment by ken107** [comment]
Thirdparty cookies definitely needed because we're using Amazon AWS Cognito for authentication and they probably use cookies to maintain login state.

I just tested on my computer. Entering correct credentials works, entering incorrect credentials results in that unhelpful error message "Authorization page could not be loaded".

If you want, you can share the credentials with me and I can check whether it works outside of your school network.  Or just give me the email login, I can at least check whether the email is in the database.  Send it to support@readaloud.app

**Comment by Gbtolvudeild** [comment]
> If you want, you can share the credentials with me and I can check whether it works outside of your school network. Or just give me the email login, I can at least check whether the email is in the database. Send it to [support@readaloud.app](mailto:support@readaloud.app)

Thanks ken107,  I just sent you an email :)
