### ISSUE TITLE
[Feature request] Allow export/import of settings

### ISSUE THREAD

**Issue by glottisfaun0000** [ken107/read-aloud#398]
Using ReadAloud across multiple Firefox instances, it would be nice to be able to backup/restore settings say from a json file that could be exported, so once I have settings where I like them on one instance I can quickly duplicate it to another. Even if you decided to exclude the API keys for security reasons, it would still be useful.

**Implementation**: In Options, an additional button next to Test and Reset to Export/Import settings

**Comment by ken107** [comment]
Thanks for the suggestion.  The settings is not complex enough yet at this time to warrant a import/export feature.  Additionally, a voice that's available on my machine may not be available, or not yet installed, on another.  So saving the voice settings may not work correctly.
