### ISSUE TITLE
Đọc lặp lại từng câu để hỗ trợ luyện nghe.

### ISSUE THREAD

**Issue by trionline1234** [ken107/read-aloud#399]
Em chào anh ạ,
Em nghĩ sẽ tốt hơn cho việc luyện nghe của người học ngoại ngữ  nếu extension mình có thể đọc lặp đi lặp từng câu với một số lần cài trước với sự hỗ trợ của giọng đọc tự nhiên của AI, đặc biệt là trong văn bản song ngữ.

Nghĩa là với mỗi cặp câu song ngữ được dịch nhờ các extension khác như Immersive Translate hay Biread, đầu tiên tool sẽ đọc câu tiếng việt trước khoảng 1-2 lần(để người nghe hình dung ngữ cảnh trong đầu), sau đó sẽ đọc câu tiếng Anh tương ứng với các tốc độ khác nhau cài trước chẳng hạn khoảng 6 lần với tốc độ lần lượt là 0.7x 0.7x 1x 1x 1.5x 2x để tập shadowing và tạo phản xạ nghe. Ngoài ra nếu câu đó dễ quá thì người đọc có thể nhấn phím tắt để chuyển sang cặp câu khác.

Rất mong anh có thể phát triển chức năng này ạ, vì giờ việc đọc báo song ngữ đã rất phổ biến với rất nhiều công cụ như Immersive Translate, Biread, ZipzapAI,.... ạ.
Nếu có donate thì mong anh cho em tài khoản, em sẵn sàng donate, thậm chí đóng phí để mua quyền sử dụng nếu anh phát triển được tính năng nâng cao này ạ.
Em cảm ơn anh.

**Comment by ken107** [comment]
Chức năng hỗ trợ học song ngữ không thuộc phạm vi của tiện ích này á bạn.  Nên để một tiện ích khác chuyên môn cho mục đích học song ngữ.  Thực hiên các chức năng này vào sẽ làm rối giao diện.  Ngoài ra, đa số các giọng đều không hỗ trợ đọc từng câu, chỉ đọc nguyên đoạn văn thôi, nên ko lặp lại từng câu đuợc.
