### ISSUE TITLE
Add support for using ElevenLabs API please

### ISSUE THREAD

**Issue by jkyndir** [ken107/read-aloud#404]
As the title says, it'd be great if voices from Eleven Labs can be used via its API.

**Comment by ken107** [comment]
Could you do a rough estimate of how many articles per day you will be reading aloud?  And from there calculate how many characters of text you will be synthesizing per day?  Let's say a typical news article is about 1500 words or 6000 characters.

**Comment by jkyndir** [comment]
it depends, maybe 5-10 articles. but typically, i will skim stuff when reading aloud

**Comment by ken107** [comment]
5 articles/day is about 30,000 characters/day, which is about 900,000 characters/month.

ElevenLabs Pro plan only gives you 500,000 characters/month. So you'll need the Scale plan which costs $330/month.

**Comment by jkyndir** [comment]
You do have a good point. Elevenlabs is indeed pricey.
I'm still trying to find an open-source/affordable TTS alternative that is easy to use and sounds really natural. Guess i can't have it all, lol.

BTW, dunno if it'd be possible to add support for this: [edge-tts](https://github.com/rany2/edge-tts), which is free Microsoft Edge TTS. Their voices do sound nice.

**Comment by jkyndir** [comment]
@ken107 
hi there, first of all, big thanks for all your hard work! Your extension is the only one out there that can read Google Play Books aloud from my library, which is simply amazing! You have no idea how much trouble you've saved me.

As mentioned in the comment above, I noticed Microsoft Edge offers free TTS voices that sound incredibly natural, almost as good as OpenAI/11labs. And it looks like these could be integrated into a Chrome extension. Here's an example I found: [ms-edge-tts-text-to-speec](https://chromewebstore.google.com/detail/ms-edge-tts-text-to-speec/oajalfneblkfiejoadecnmodfpnaeblh). But that extension is missing a lot of essential features and is really tough to use.

Any chance you could look into adding these Microsoft Edge voices to your extension? Thanks!

**Comment by jkyndir** [comment]
Just found out when installing your extension in the Edge browser, all those MS Edge natural voices become available by default, which is amzing!

But still, i wonder if it's possible to have them available in Chrome browser as well? since that's my main.

**Comment by ken107** [comment]
#391 I think probably possible, we'll check out and add it in a future release.  Thank you for your feedbacks.
