### ISSUE TITLE
Make text in popup window copyable

### ISSUE THREAD

**Issue by atkirtland** [ken107/read-aloud#408]
If the popup window is treated like a reader mode, then it would be convenient to be able to copy text by clicking and dragging.

**Comment by ken107** [comment]
Please copy the text directly from the webpage article or document instead of the popup window.  The text in the popup window supports click-to-seek behavior.  Therefore it cannot support text selection

**Comment by atkirtland** [comment]
It's perfectly fine for it to not be planned, but why is there a fundamental conflict between click-to-seek and text selection? Is it a technical limitation with the libraries used? When I click and drag now, nothing happens. It does not seek. It therefore seems like clicking and dragging could be used for text selection.

**Comment by ken107** [comment]
You are right, it's possible to support both behaviors. In this case, i think it's just not a good place to do text selection. The content in the popup is too dynamic, with text highlighting, auto-scrolling, and click to seek behavior.
