### ISSUE TITLE
Unable to read the simplest files

### ISSUE THREAD

**Issue by pistou** [ken107/read-aloud#413]
Here is a basic sample code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lorem ipsum</h1>

    <form method="POST" action="">
        <input id="check1" type="checkbox" value="1" aria-labelledby="check1-label" />
        <label id="check1-label" for="check1">This is an input label</label>

        <button type="submit">Submit</button>
    </form>
</body>
</html>
```

ReadAloud is unable to read anything on this file. On a more general note, it seems to ignore anything in a form.

**Comment by darvon123** [comment]
that is pretty normal behavior for a text-to-speech service to do. 
some form inputs can have trigger effects set on an in-focus action especially for mobile browsers where the only input method available is touch. a lot of webpages have their mobile versions loaded offscreen but is a tab key away from being triggered.
