### ISSUE TITLE
Volume slider barely does anything, still too loud even when it's set to 0

### ISSUE THREAD

**Issue by Yasand123** [ken107/read-aloud#420]
At least on Firefox, the volume slider works but it seems it goes from 70 to 100 and not from 0 to 100 as you'd expect. At the lowest it's still way too loud.

**Comment by ken107** [comment]
Volume goes from 20% to 100%
https://github.com/ken107/read-aloud/blob/fd2595d17ab3c83d6acab01d3be2a3e8b35bb41c/options.html#L79
