### ISSUE TITLE
Add support for Elevenlabs voices

### ISSUE THREAD

**Issue by superluig164** [ken107/read-aloud#429]
I'd love to see support for Elevenlabs TTS in Read Aloud (through entering an API key similar to the other advanced voices.)

**Comment by superluig164** [comment]
Oof, any particular reason?

**Comment by ken107** [comment]
Ah, we only add support for voices that are priced at $16 per million characters or less.  Anything above that is unsuitable for general article/document read-aloud purpose.

Many of the new AI TTS services are geared towards commercial purposes.  For example, they use ElevenLabs to synthesize a short audio advertisement.  Then the advertisement is played again and again on TV, radio, embedded into website, etc.   The pricing is very high for these commercial usage.  ElevenLabs' pricing is one of the most expensive.

**Comment by superluig164** [comment]
Sure, but if the user enters their own API key and pays for it, surely the option would be appreciated?

**Comment by ken107** [comment]
Nobody will actually use it, and so it will not be worth the effort. If someone uses it they will only use it for a short time, because it costs too much for extended use.

**Comment by mysticaltech** [comment]
I would definitely use it. I need to find a way to use my elevanlabs credits.
