### ISSUE TITLE
Is it possible to cast to other devices?

### ISSUE THREAD

**Issue by chew-z** [ken107/read-aloud#43]
I couldn't make it work with my speaker. Chromecasting would be logical extension of functionality I guess.

**Comment by ken107** [comment]
Thank you for the suggestion, sorry I wasn't quite sure how to do this, so I kinda forgot about it.

We can't do this with browser's built-in voices, only with cloud-generated voices.  But even then, the audio is broken up into small segments, which we have to join before sending to Chromecast.  Joining needs to occur on the server.

All in all, I'm afraid the effort is not worth it at this time.
