### ISSUE TITLE
Piper Voices working on android?

### ISSUE THREAD

**Issue by anaxonda** [ken107/read-aloud#431]
Are piper voices able to work on android? Running read-aloud on Mull (fennec) browser.

I'm able to install them in piper.ttstool.com, select them in the read-aloud extension menu. In the activity log on piper.ttstool.com I have `Synthesizing $article using $pipervoice...` , but followed by `Error: no available backend found. ERR: [wasm] ReferenceError: WebAssembly is not defined, [cpu] Error: previous call to 'initWasm()' failed.`

**Comment by ken107** [comment]
Looks like the browser doesn't have WebAssembly support
