### ISSUE TITLE
Right click context menu entry disappeared, unable to use for reading text in my preferred PDF engine

### ISSUE THREAD

**Issue by AlizeeFR** [ken107/read-aloud#432]
![image](https://github.com/user-attachments/assets/8e4bbfda-4e3b-4c7f-807d-b228fa74549c)

I like using microsoft edge's built-in PDF viewer & editor since it lets me highlight and add YouTube videos as comments directly to PDF files. Prior to the November 27th update, I had been able to right click and have selected text read aloud without having to upload my PDF through lsd software which would not use microsoft's PDF viewer. 

Ideally, I'd be able to just use the shortcuts without having to right click, but I was happy to use the right click as a workaround. This is no longer possible as of today

**Comment by ken107** [comment]
What do you see when you right click on the selected text?  It's working fine for me.

![image](https://github.com/user-attachments/assets/3fca357c-02bb-4f3f-a2ba-e2abea9c552c)

**Comment by ken107** [comment]
Try uninstalling and reinstalling the extension if you don't see the context menu

**Comment by AlizeeFR** [comment]
uninstalling and reinstalling worked. thank you!
