### ISSUE TITLE
Reading speed for each language

### ISSUE THREAD

**Issue by ShohruxYusupov** [ken107/read-aloud#435]
I read articles in two languages. I set the speed to 1.5, which is comfortable for me, for the first language. However, for the second language, it feels a bit slow.
If users could adjust the reading speed for each language (as they can do with Voice option), this problem would be solved.

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implemented language-specific rate settings in the options page. Users can now set different speeds for different languages. The rate slider and input now update based on the selected language, and the settings are stored separately for each language.

You can review changes in this commit: https://github.com/zxsa89675/ken107-read-aloud-435/commit/28c69ab05e7ca5ee74589435799b92c22b183ee7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ShohruxYusupov** [comment]
There's no need for an additional speed slider in the main menu, which could confuse users. Instead, you could add it to a menu where users set the voice engine for each language.
