### ISSUE TITLE
Đọc song ngữ từng cầu với Google Dịch

### ISSUE THREAD

**Issue by trionline29** [ken107/read-aloud#44]
Chào anh, em thiết nghĩ tại sao phần mềm này không nâng cấp để có thể tự động đọc phần dịch của Google và phần câu nguyên gốc xen kẽ từng câu như vậy sẽ giúp cho người dùng có thể vừa đọc tin tức vừa học từ vựng với bất kỳ ngôn ngữ nào ạ.
Xin chân thành cảm ơn anh về phần mềm hữu ích này.

**Comment by ken107** [comment]
Chào bạn, mục đích chính cũa phần mềm này là đọc to bài viết cho người nghe.  Nếu muốn dùng cho học tiếng anh thì chắc phải làm một app riêng.

Ý kiến bạn hay đó, nhưng mình không rõ ứng dụng thế nào.  Không thì có thể làm 1 app chuyên cho mục đích đó

**Comment by trionline29** [comment]
Em nghĩ có thể tích hợp vào extension này luôn thì tốt ạ, giúp cho mọi người dùng có thể học bất cứ ngôn ngữ nào thông qua việc đọc tin tức.
Đầu tiên sẽ nghe câu dịch, sau đó người đọc hình dung ngữ cảnh rồi máy tự đọc luôn câu gốc tương ứng theo sau đó, cứ thế đọc song ngữ qua từng câu một. Phương pháp này vừa nghe tin tức, học từ vựng, luyện nghe, 3 trong 1 thì còn gì bằng.
