### ISSUE TITLE
Read-aloud  changes the settings for browser system web text to speech.

### ISSUE THREAD

**Issue by 1der1** [ken107/read-aloud#52]
Our website builder at 1der1.com adds text-to-speech to all created pages unless you choose to silence it.

After adding the Chrome read-aloud extension, we noticed that our text-to-speech had more than 170 voices in the list instead of the usual 20 - wonderful.

However, the installation of read-aloud changes the default Chrome setting for speed. Our pages speak slower than usual now. The slower voice is sweet for some languages (like English), but others sound intoxicated, for example, the female German Google voice. You can check this here:

https://1der1.de/mercedes-benz

You have to add German to your browser languages to hear the German voice.
If you have English in your Chrome setting, you will hear the German text pieces with the German voice and the English fragments with an English voice. All languages are supported on a page if there is a matching voice in the list.

BTW: Firefox stays with the feeble Microsoft Windows system voice "Anna".

**Comment by ken107** [comment]
Ah, I think I know what you're talking about.  I'm actually in the process of making some changes that would solve your problem.  I'll let you know when I'm done so you can test it.

**Comment by ken107** [comment]
OK, I have deployed the update.  The voice should speak slightly faster now.  Please try it out.

Also, it's not that the extension is changing the Chrome speed setting.  Here's what happen:  On your website you probably implemented some algorithm to pick one of the 170 voices available depending on the language.  It happens to pick the "GoogleTranslate German" voice.  This voice uses https://translate.google.com.  If you go to that website, type in some German text and click the speaker button, you will see that it speaks very slowly.  That's the reason.

So the fix I've put in is to use audio tools on the server to speed up the audio.  If you think it is still too slow, let me know.  I can make a special case for the German language.

**Comment by 1der1** [comment]
Thank you, it is great now. There is still a difference in speed when the extension is installed but the result is very good.

BTW: Is there a possibility to use the additional voices even when the website visitor doesn't have the extension installed? Thank you.

**Comment by ken107** [comment]
Yes, if you use the Read Aloud embed script from here: https://ken107.github.io/read-aloud/

Right now the embed code doesn't let you to choose a specific voice, but I'm making changes that will let you do that.  Stay tuned.

**Comment by ken107** [comment]
If you need to provide TTS for your website, please try https://www.sitespeaker.com/
Direct signup link: https://dashboard.sitespeaker.com?p=SignUp

Note that SiteSpeaker is in Beta and we're not yet charging for this service, but eventually will.  The price table mentioned on the main site is not final.  We'll actually be adding a bottom tier that use browser's built-in TTS by default, and that will be priced at around $4.99/m.
