### ISSUE TITLE
Right click read aloud stops after about 80 words

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#56]
There are scattered reports of this issue, on Chrome.

**Comment by natewillett1996** [comment]
Is there any work around for this?

**Comment by ken107** [comment]
As workaround, after selecting text, please click the Read Aloud icon instead of using the context menu

**Comment by krystian3w** [comment]
I have these bug on Firefox and I must remove (reinstall) addon to back option in context menu.
