### ISSUE TITLE
Read aloud not working on any website

### ISSUE THREAD

**Issue by orschiro** [ken107/read-aloud#59]
Dear @ken107 et al, 

I just reinstalled the extension again after a while of not using it. 

I found that no audio is played for any website. Not for text selections, neither for the whole page.

Am I missing something? Do I need to setup something in addition to make it work again?

Yours

![screenshot_2018-09-25_09-22-26](https://user-images.githubusercontent.com/170947/46014120-a3330700-c0a4-11e8-83f2-4ad9d55d2dcc.png)

![screenshot_2018-09-25_09-22-50](https://user-images.githubusercontent.com/170947/46014142-afb75f80-c0a4-11e8-8a68-27ea193d9d20.png)

**Comment by ken107** [comment]
Hi Robert, long time!

From the screenshots it looks to be reading, but apparently you hear no sound.  Looks like the browser's built-in voice engine is not producing sound.  I've had similar issue reports on Mac OS. 

Could you try selecting other voices see if they work?
Also, you can use this website to try out the different voices available and see which one specifically has problem:  https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/speechsynthesis/

**Comment by orschiro** [comment]
Dear @ken107, thank you for your swifty reply! I can confirm that it works now with `Microsoft US English (David)`. To the contrary, `Google UK Male` does not work. 

Yours
