### ISSUE TITLE
Never reads page

### ISSUE THREAD

**Issue by Propain6** [ken107/read-aloud#6]
I have tried several pages and when I click the button, it doesn't read anything, just gives me a link to report a problem.

**Comment by ken107** [comment]
Could you tell me what URL you were trying to read?

**Comment by Propain6** [comment]
https://redmondmag.com/articles/2015/06/03/features-to-sql-server-2016.aspx?m=1



On Sat, Jan 7, 2017 at 2:23 AM -0500, "Hai Phan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you tell me what URL you were trying to read?

**Comment by ken107** [comment]
Thank you.  I've put in some fixes (f16b2c) and your URL seem to work fine now.  Closing ticket
