### ISSUE TITLE
Put Volume/Speed options on the main popup?

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#61]
Perhaps other options too

**Comment by ken107** [comment]
Customer also asks for hotkeys to change speed on the fly

**Comment by ken107** [comment]
For changing speed/volume, for cloud-based voice, can change audio-file playback speed/volume in real-time.  For native voice, can restart playback from beginning of paragraph

**Comment by dzeruel** [comment]
Hi! Excellent news, when will this be released to the chrome web store?

**Comment by ken107** [comment]
Well, when we have a number of things in this milestone, it's gonna take some time.  Sorry about that.

**Comment by dzeruel** [comment]
Hello Ken, 

Could you please implement this?

**Comment by syffs** [comment]
@ken107 I must say this extension is amazing. I'm a multi-tasker, my productivity lies on being able to do at least 2 things at the same time. I can listen to podcasts or youtube on x2 speed, but anytime content wouldn't be available through audio, I'd basically be wasting time/productivity/money ! Thanks for this

Anyway, the core value of such extension is to have a media player (like youtube or any podcast player) for text, Hence IMO, like any good media player out there, being able to set volume and speed in 1 click are the last 2 features it needs.

any idea when this'll be available ?

**Comment by ken107** [comment]
I'm not clear how to implement this yet.  For the built-in voices, you have to stop and restart reading to change the speed and volume.  So maybe only show the controls when user clicks Stop, not while speech is playing.  Also the controls will take up the limited space available in the popup, which is used for the text highlighting.

**Comment by ken107** [comment]
To think about it, we could put put small gray gear icon top right corner of the popup, visible only when it's possible to change speed on-the-fly.  Clicking icon could show the speed slider below

**Comment by ken107** [comment]
Merged into #247
