### ISSUE TITLE
Rewind is full of glitches

### ISSUE THREAD

**Issue by pal1000** [ken107/read-aloud#66]
As pointed out in this review https://addons.mozilla.org/en-US/firefox/addon/read-aloud/reviews/1206304/ rewind is glitched in many ways:
- it just moves the color highlight to previous paragraph instead of also suspending speech and restarting from previous paragraph;
- when rewind has been pressed at least once the stop button starts behaving like forward instead of stop reading;
- when rewind has been pressed at least once the extension reads the whole selected text 2 times instead of only once.

[TTSFox](https://github.com/ettoolong/TTSFox) another extension with lower popularity handles rewind and forward in a very neat, probably simpler and even more powerful way by allowing to pick any paragraph when paused using pointing device or touch interface.

**Comment by ken107** [comment]
Thank you.

The rewind actually is fine.  But the browser's built-in voices don't respond immediately to stop, causing delays and weird result.

Though if you have the highlighting turned on, you can also click on a paragraph to skip to it.  I think will make it clearer for users

**Comment by pal1000** [comment]
Unfortunately selecting the paragraph has the same problem. It only impacts the text highlighting, reading continues onward. TTSFox provides rewind only when paused and never when reading to avoid built-in voices unresponsiveness.  I tried to use it the same way as TTSFox: pause then pick paragraph. Text highlight responds to it pretty well, but reading continues onward.

**Comment by ken107** [comment]
I'll have a look, thanks

**Comment by ken107** [comment]
Well, we finally fixed it with ede59dfdb142e2ab8ce064780fee7061549a0314
Please try again and let me know if u still have the issue.

**Comment by pal1000** [comment]
Yes this is indeed fixed.  Now if #110 is addressed too, it would definitely make it my favorite Firefox TTS extension as it asks for least permissions and still gets the job done. Though I have to admit TTSFox only asks for browser tabs access which isn't much worse either.
