### ISSUE TITLE
Can we queue the selected text to read once the current one finishes?

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#72]

**Comment by ruffsl** [comment]
One behavior I'd like to change for queuing is that: if while listing to selected passage of text, should the user update/change the selection of text, then pressing the play/pause key-shortcut should cancel the reading for the previous selection and start anew from the current selection, **instead** of just restarting from the beginning of the previous selection as it does now.

It's currently not very intuitive, as to get the extension to read from the new selection, one must first manually stop reading from the previous passage, the go back to re-select the new text, then press play again. It's a bit tedious to repeat every time when skimming larger documents.
