### ISSUE TITLE
Search/Replace in text

### ISSUE THREAD

**Issue by ken107** [ken107/read-aloud#87]
Perhaps a button on the popup to replace all occurrences of some word with another (with regex option).  To allow advanced users some control over the text to be read.

Edit: Advanced Options

**Comment by escape0707** [comment]
The search feature on its own is a very useful feature when you were in the middle of a very long page and want the extension to start read aloud from there.

If https://github.com/ken107/read-aloud/issues/50 is too hard to implement without the help from firefox side, then is feature could be a good workaround.

**Comment by ken107** [comment]
Will implement a replacement table, see #208
