### ISSUE TITLE
Icono en la barra de chrome

### ISSUE THREAD

**Issue by agcoaching** [ken107/read-aloud#9]
Hola, he instalado Texto a voz, lo eliminé y lo he vuelto a instalar pero no despliega la botonera. Al hacer click no hace nada. Cual puede ser mi error?
Gracias

**Comment by ken107** [comment]
Hola, ¿todavía tienes este problema? Si no puede ver el botón, por favor, dígame la versión de Chrome. Asegúrese de actualizar a la versión más reciente. ¿Podría publicar una captura de pantalla?
