### ISSUE TITLE
Kiwi Browser Extension Issue

### ISSUE THREAD

**Issue by NatalieRath** [ken107/read-aloud#90]
I keep getting this error.

Cannot access contents of the page. extension manifest must request permission to access the respective host.

Please help.

**Comment by ken107** [comment]
Really sorry we couldn't help you in time.  I've tested Read Aloud on the Kiwi browser on my Android and it seems to work fine.  It is possible you were in Reader mode, or using another extension such as an EPUB reader, when you activated Read Aloud.

When this issue occurs, please check your URL and make sure it is an http:// or https:// URL and not something else.  Extensions in general cannot access the text content of other extensions.  So Read Aloud only works on web pages directly.
