### ISSUE TITLE
Microsoft Azure Cognitive Services Speech Services APIs support?

### ISSUE THREAD

**Issue by KopWang** [ken107/read-aloud#92]
Hey guys, I noticed that only AWS credentials and Google GCP API key are available in 'Custom Voices'. No Azure API Key.

For me, the new Neural voice by Microsoft is super awesome. I bought it on Azure.

So can I use my own Azure API Key to enable Neural voice? Will this be supported in Custom Voices in the future?

Thank you : ).

**Comment by ken107** [comment]
Sure!  I'll try to get to this soon.

**Comment by ken107** [comment]
fixed by 6db16a8
