### ISSUE TITLE
Can't read from DOM distiller

### ISSUE THREAD

**Issue by redbrain** [ken107/read-aloud#93]
In Google Chrome, people using the experimental feature "--enable-dom-distiller" can activate [a sort of read mode from the context menu](https://www.pcworld.com/article/2889207/how-to-enable-chromes-clutter-free-experimental-reading-mode.html). These pages begin with "chrome-distiller://" and the extension returns this error message when I click on it: 
![image](https://user-images.githubusercontent.com/42494361/57885274-91030600-77f8-11e9-9361-6625e25b7ea5.png)
Is this fixable?
###### Thanks.

**Comment by ken107** [comment]
At this time I don't think it's possible to inject content script into chrome-distiller:// URLs.  We'll keep this open and explore how integration could be enabled.

**Comment by redbrain1014** [comment]
Until this is possible, you can work around this by having the extension start reading the page before you distill it. The extension will keep reading and the distilled page displays.
