### ISSUE TITLE
Add wavenet api key as custom voice 

### ISSUE THREAD

**Issue by owopeachy** [ken107/read-aloud#95]
how exactly do i go about adding my gcp api key to allow my wavenet voices to work? the inbuilt option that makes you do the captcha worked once but wont work anymore

**Comment by owopeachy** [comment]
i figured it out, apologies

**Comment by ken107** [comment]
You say the captcha no longer works?  Can you describe what happens with the captcha now?

**Comment by owopeachy** [comment]
Well, I had GoogleStandard voice selected, and it read out one page fine,
then when i went to the next page in the same site, it said it needed the
permissions, took me to the google page, gave the instructions at the top
of the page as usual, but when i followed them and passed the captcha it
just didnt work, gave the same error and still said it needed permissions.
In the end though i found how to get my cloud api to work so i have wavenet
voices working again.

**Comment by thoka** [comment]
> i figured it out
Could you describe, how to do it ?

**Comment by MikeStirner** [comment]
I was getting the 403 error after entering my API key but then I asked GPT-4 and it told me to enable a new API service "Cloud Text-to-Speech API" and that fixed it. I was also signed in, but not sure that mattered.

**Comment by bobpaul** [comment]
> > i figured it out
>
> Could you describe, how to do it ?

So here's what I did:

1. Go to https://console.cloud.google.com/
2. Create a new project for my copy of readaloud to use
3. Go to the [API Dashboard](https://console.cloud.google.com/apis/dashboard) (make sure the project you made is selected at the top of the screen) and enable the Cloud Text to Speech.
4. Go to the [Crendentials Dashboard](https://console.cloud.google.com/apis/credentials) (make sure your project is still selected at the top of the screen) and create a new API key.
5. (optional, but recommended) After the API key is created, edit the API key and restrict its access to the "Cloud Text to Speech" api. (You can set "Application restriction" to none and "api restriction" to the text to speech api.)
6. Paste the API key into the extension settings.
