### ISSUE TITLE
Test button hung

### ISSUE THREAD

**Issue by onebod** [ken107/read-aloud#96]
Clicked Test button - on a Google UK Bain voice, it threw an error over the top of the buttons.
On another Google voice, clicking the Test button just makes a circle go round instead of the Test Button.
Now the only available voice listed is Auto Select, and even after disabling and enabling add-on, it's still going round.
Getting close to giving up on this add-on - I want offline voices, additional MS voices are impossible to install, it shouldn't be this hard.

**Comment by ken107** [comment]
Ah, yes, I published v1.11.0 the other day after putting back GoogleWavenet voices.  I forgot to make it work in the Options page.  Later today, I'll publish version 1.12.0.  Please be sure to get that version

**Comment by ken107** [comment]
Let me know if you still have this issue, thanks

**Comment by onebod** [comment]
Just tried to test - couldn't find the voice called Bain, but tested a few. The test didn't hang.
I did have to go through the Speak-It, I'm not a robot thing on the google page, but I think I opened another issue about having to do that every time I wanted to use it, so seems like this issue can stay closed.
